---
title: AMD also seems to be floundering
author: Seth Green
date: '2024-08-14'
slug: amd-also-seems-to-be-floundering
categories: []
tags: []
---

Intel recently announced a plan to eliminate [15,000 jobs](https://www.extremetech.com/computing/intels-day-of-reckoning-arrives-15000-jobs-will-be-eliminated) after historically bad quarterly results.

It's been rehearsed to death that Intel missed the boat on [mobile](https://techcrunch.com/2016/05/17/how-intel-missed-the-iphone-revolution/) and [AI](https://fortune.com/2024/08/07/intel-ai-openai-chips-investment/), but execution issues seem just as important. When Apple [ditched Intel](https://www.anandtech.com/show/16226/apple-silicon-m1-a14-deep-dive) for its own processors in 2020 to [glowing](https://www.anandtech.com/print/17024/apple-m1-max-performance-review) [reviews](https://www.tomshardware.com/reviews/macbook-pro-m1-13-inch-2020), the root cause was [quality assurance](https://www.techpowerup.com/269024/bad-intel-quality-assurance-responsible-for-apple-intel-split). Even if Apple was a [small, disproportionately difficult customer](https://www.marketwatch.com/story/in-this-case-losing-apple-as-a-customer-would-be-good-news-2020-06-15), I think that more alert leadership would have seen their departure as the canary in the coal mine and moved heaven and earth to fix QA. Instead, four years later, Intel's desktop chips are still having [serious stability ](https://www.tomshardware.com/pc-components/cpus/intel-announces-an-extra-two-years-of-warranty-for-its-chips-amid-crashing-and-instability-issues-longer-warranty-applies-to-13th-and-14th-gen-core-processors)[problems](https://www.tomshardware.com/pc-components/cpus/intel-announces-an-extra-two-years-of-warranty-for-its-chips-amid-crashing-and-instability-issues-longer-warranty-applies-to-13th-and-14th-gen-core-processors), and other laptop vendors [are](https://www.tomshardware.com/laptops/ultrabooks-ultraportables/microsoft-surface-pro-2024-review) [jumping](https://www.tomsguide.com/computing/laptops/asus-vivobook-s-15-snapdragon-x-elite-review) [ship](https://www.pcworld.com/article/2415368/dell-inspiron-14-plus-7441-review-another-copilot-pc.html).

To round out the picture, Intel's next generation of chips is [expected to have unusually high production](https://www.tomshardware.com/pc-components/cpus/intel-lunar-lake-is-almost-entirely-outsourced-as-panther-lake-and-clearwater-forest-get-powered-on) costs, its GPUs have made [essentially zero inroads](https://www.pcgamesn.com/intel/gpu-market-share), and it's losing ground to AMD in both the [server](https://www.tomshardware.com/pc-components/cpus/amd-records-its-highest-server-market-share-in-decades-but-intel-fights-back-in-client-pcs) and [desktop](https://www.tomshardware.com/pc-components/cpus/amd-takes-cpu-market-share-from-intel-in-desktops-and-servers-but-intel-fights-back-in-laptops) markets. A lack of strategic vision combined with inability to execute has the marks of a death spiral.

But the thing is, from what I can see, AMD is not exactly hitting it out of the park either. I started paying attention to this when I looked into buying a mini-PC in early 2024. I wanted something approximately the size, price, and performance of a Playstation 5 but with a bit more flexibility. My thought was that with the PS5 released nearly 4 years ago, and with processors expected to double in performance every 18 months, I could find something.

In January 2024, AMD released two processors, the 8700G and the 8600G, that looked well-suited for this on paper. They're both APUs ("[Accelerated Processing Unit](https://en.wikipedia.org/wiki/AMD_APU)" — who comes up with these names?) with CPUs and GPUs on a single die, aimed as the low-power home PC gaming market. But they both got [pretty](https://www.techspot.com/review/2796-amd-ryzen-8700g/) [tepid](https://www.tomshardware.com/pc-components/cpus/amd-ryzen-5-8600g-cpu-review) reviews because their price propositions don't work.[^1] Then, In July, AMD released a laptop processor that [outperforms](https://www.anandtech.com/show/21485/the-amd-ryzen-ai-hx-370-review/9) those two processors handily with lower power consumption.

[^1]: If you want to play games cheaply, you can do much better with a [few other CPU/GPU combinations](https://www.tomshardware.com/pc-components/cpus/amd-ryzen-7-8700g-cpu-review); and if you the smallest possible PC, buy [one of many prebuilt mini PCs](https://minipcs.org/) from manufacturers in China that mostly use AMD's laptop parts. Either way, won't get anything nearly as good as a 4-year old gaming console, which continues to confuse me.

So what exactly was AMD thinking when it released the 8700G and 8600G? Why did it release overpriced products and then make them obsolete 6 months later?

One explanation is that big companies are like octopuses, and each product division/arm is [essentially its own brain](https://www.scientificamerican.com/article/the-mind-of-an-octopus/) with its own reward structures. I think this model works pretty well for Google, where product shutdowns are [depressingly regular](https://gcemetery.co/google-product-lifespan/) (people set up [websites to count down to cancellation](https://news.ycombinator.com/item?id=21596003)) and generally attributed to [misaligned incentives](https://www.warp.dev/blog/problems-with-promotion-oriented-cultures). But AMD's issues seem to be less about multiple aims and more about incoherent go-to-market (GTM) strategy. Using low-power, integrated chips to away at Nvidia's market share at the low end was and is sensible. But if the chips have the wrong price considering the expensive complementary products required (a new motherboard and faster RAM), then it won't sell.

Some other places where we see this kind of inattention to GTM:

-   AMD's [naming](https://imgur.com/2ab20Zc) [scheme](https://www.reddit.com/r/laptops/comments/yh89xo/what_does_the_letter_x_g_u_h_hs_mean_on_a_ryzen/) for its laptop parts is truly a marvel of impossible to remember terms. Why make this hard for buyers? (This is a surprisingly common problem among manufacturers — what does "[G34WQi](https://www.tomshardware.com/monitors/gaming-monitors/xiaomi-g34wqi-34-inch-180-hz-gaming-monitor-review)" evoke for you?)

-   Its most recent flagship desktop processor is getting [mixed to negative reviews](https://www.extremetech.com/computing/flagship-amd-zen-5-ryzen-9-9950x-cpu-reviews-are-a-mixed-bag) because it is, again, priced wrongly (and also beset by unexplained performance issues and a [serious driver issue](https://www.tomshardware.com/pc-components/cpus/amd-ryzen-9-9950x-cpu-review/5) that's lasted for \~16 months)

-   The company continues to [lag badly](https://www.techradar.com/computing/gpu/nvidia-now-owns-88-of-the-gpu-market-but-that-might-not-be-a-bad-thing-yet) in the AI/GPU market in large part [because its software](https://news.ycombinator.com/item?id=39344815) isn't competitive.[^2]

[^2]: Lisa Su says, about her experiences with the Playstation 3: "[Perhaps one could say, if you look in hindsight, programmability is so important](https://stratechery.com/2024/an-interview-with-amd-ceo-lisa-su-about-solving-hard-problems/)." Ok, so how about we apply those lessons to current products...

Basically, I see a company that capitalized on its main competitor's struggles and continues to release some very [successful](https://www.anandtech.com/show/16217/the-xbox-series-x-review-ushering-in-next-gen/2), [specialized](https://www.tomsguide.com/news/ps5-pro) products, but that seems to be its own worst enemy in terms of GTM. (Some might attribute this to having a [CEO who specializes in hardware](https://stratechery.com/2024/an-interview-with-amd-ceo-lisa-su-about-solving-hard-problems/) rather than business.) I think this has gotten less attention than it might in light of Intel's more obviously existential struggle. But inability to market and sell the right products to the right customers is also a serious crack in the foundation.

Intel might be too big and too moribund to save. But if I were tasked with fixing things at AMD, I would say:

-   Get the product marketing right. Name the products simple, memorable things. Look at Apple.

-   If the price proposition doesn't work, subsidize. Sell the 8600G at a loss and make future processors backwards compatible and encourage upgrades.

-   Make the AI software work.

But who knows? I am just seeing a small part of the puzzle. I will continue to watch with interest.
