---
title: Opposition to unplanned progress, bedrock of our politics
author: Seth Green
date: '2020-08-13'
slug: we-lack-a-consistent-term-for-people-who-oppose-unplanned-progress
categories: []
tags: []
---

An article in the _Times_ reports local opposition to [redeveloping Industry City in Brooklyn](https://www.nytimes.com/2020/08/12/nyregion/industry-city-zoning-amazon-nyc.html). In [Councilman Menchacha's letter on the subject](https://mailchi.mp/council/phase-2-reopening-updates-1041606):

> I firmly believe housing is a human right and that no one should be forced to leave their home because they can no longer afford to live in their own neighborhood....I and my team are committed to working with everyone in the neighborhood to build on a legacy of community-led and comprehensive planning that creates guaranteed housing and jobs

I hear echoes of anti-immigrant sentiment. Consider [Bernie Sanders, claiming in 2015 ](https://www.vox.com/2015/7/28/9014491/bernie-sanders-vox-conversation) that free immigration would

> make everybody in America poorer — you're doing away with the concept of a nation state, and I don't think there's any country in the world that believes in that. If you believe in a nation state or in a country called the United States or UK or Denmark or any other country, you have an obligation in my view to do everything we can to help poor people...**As a United States senator in Vermont, my first obligation is to make certain kids in my state and kids all over this country have the ability to go to college**, which is why I am supporting tuition-free public colleges and universities.

It is strange to me that people who espouse these views are labeled progressive. Progress is forward motion, it's messy, disruptive: ["All that is solid melts into air, all that is holy is profaned."](https://www.marxists.org/archive/marx/works/1848/communist-manifesto/ch01.htm) If your "first obligation" is to preserve a defined set of opportunities for a certain set of people, and to forcibly prevent others from competing for those opportunities -- on the face of it, that certainly _sounds_ like opposition to progress, right?

I disagree with Menchacha and Sanders here -- I want more progress on both fronts -- but I think I get where they're coming from. If they were proposing nonviolent means for preserving their visions of utopia, there would be no story here. But when you tell developers what they can and can't build with the NYPD standing behind you, or you forcibly close legitimate entry to would-be migrants and then torture those who try to get around the barriers you've erected, that's a different matter. 

I don't see eye to eye with most people on this. I don't see eye to eye with them on veganism either. 

I think Menchacha and Sanders would say that they have _different_ visions of progress in mind -- in Menchacha's words, they prefer "comprehensive planning" before changes happen. But if you compare their visions to the forces they oppose, I think we can safely say that they prefer quantitatively _less_ progress, less change. The word that comes to mind for preferring less change, or change more slowly ("Go slow now. Stop for a time, a moment," [counseled Faulker on the subject of integration](http://users.soc.umn.edu/~samaha/cases/faulkner_letter_northern_ed.html)) is conservative. But that's not quite right, at least in an American context; a single label that encompassed [David French](https://www.newyorker.com/news/the-political-scene/david-french-sohrab-ahmari-and-the-battle-for-the-future-of-conservatism) and Bernie Sanders would be noisier than those we have now.

We lack a consistent term for people who oppose unplanned progress. I would call them anti-liberals, or perhaps planners. But when I look at American politics, a general opposition to unplanned progress seems like [the water we swim in](https://fs.blog/2012/04/david-foster-wallace-this-is-water/), unremarked upon.