---
title: 'Kylie, standard or speciation'
author: Seth Green
date: '2026-08-27'
slug: kylie-standard-or-speciation
categories: []
tags: []
---

In _[Consider Phlebas](https://en.wikipedia.org/wiki/Consider_Phlebas)_, we learn about a band of humanoid pirates:

> Tzbalik Odraye roomed with Rava Gamdol, who looked as though he came from the same place as Yalson, judging from his skin and light fur, but he denied this...Lamm was rather below average height, but very muscular and dense looking. He had double eyebrows and small horn grafts.

In other words, (guided) speciation: specialization from a common genetic stock to meet the needs of different environments. 

This is a trope in the sci-fi books I read, e.g., the Centaurs in [_House of Suns_](https://en.wikipedia.org/wiki/House_of_Suns). It's fun to speculate about future humans choosing to evolve in ways that are interesting and bizarre, and there's something to the idea that cultures are diverse enough that we can expect modifications that don't increase reproductive fitness outside of their very narrow cultural contexts (see, e.g., foot binding).

But in today's _NY Post_ we learn that '[Kylie Jenner wants ‘bigger and more out there’ implants after sharing exact boob job specs](https://pagesix.com/2026/08/27/celebrity-news/kylie-jenner-wants-bigger-and-more-out-there-implants-after-sharing-exact-boob-job-specs).' And here I think we see a more realistic path towards what human speciation will look like. The story notes, both verbally and visually, that she's already quite buxom, but [never enough](https://open.spotify.com/track/3F3EV31axlzEEUl7MBB3Jv?si=9186ad09e6854190): "Jenner confirmed, 'I want my tits to walk in before I do.'" 

The more obvious context for understanding Jenner's boobsmaxxing is Meta's paying '[up to $18bn to settle claims its platforms harm children](https://www.bbc.com/news/articles/cd68q3wynnqo)' and the obvious implication that Jenner and her ilk are promoting unrealistic beauty standards to vulnerable youths. Yes yes, bad bad. But I am trying to think more [sci-fi thoughts](https://x.com/tszzl/status/2068409089345134984) lately, and I think Jenner harbinges the kind of speciation we'll actually see, first through common adoption and then through genetic modification. I expect the first moves here to be hugely exaggerated primary and secondary sex characteristics that transcend particular cultures. We'll see things that signal fertility while perhaps actually diminishing it (implantis that impede access to mammary glands, vaginas too narrow for birth, penises too large for most partners).

I do not cheer this future. I don't think it gets us closer to [being attack helicopters for a day](https://www.theguardian.com/books/2020/jan/17/sci-fi-magazine-pulls-story-by-trans-writer-after-barrage-of-attacks), which would rule. But I think [things are going to get weird](https://acotra.substack.com/p/til-death-or-the-singularity), and that Kylie gives a hint of what to expect. 