---
title: Five agreeable-sounding propositions about housing
author: Seth Green
date: '2024-05-15'
slug: agreeable-housing-propositions
categories: []
tags: []
---

Bryan Caplan asks us to think about [ending zoning](https://reason.com/2024/05/07/rent-free-qa-bryan-caplan-on-build-baby-build/), while [Manville, Monkkonen & Lens (2019)](https://www.tandfonline.com/doi/full/10.1080/01944363.2019.1651216) advocate for ending single-family zoning. I share these priorities, but I think they sound disruptive. Here are five propositions about housing and construction that, I hope, sound more agreeable. 

1. If a single-family home is ok, a [duplex](https://missingmiddlehousing.com/types/duplex-side-by-side), [triplex](https://missingmiddlehousing.com/types/triplex), [in-law suite](https://www.strongtowns.org/journal/2024/3/15/an-adu-called-by-any-other-name), or [cottage court](https://missingmiddlehousing.com/types/cottage-court) are all probably ok too.^[I dream of a cluster of tiny homes near a lake somewhere where my friends and I can hear frogs at night and be within walking distance of the Seth's Six Essential Amenities: Trader Joe's, cafe, restaurant, brewery, climbing gym, and movie theater. (Indie _and_ mainstream movie theaters if I am being greedy.)]  

2. Cities with a [wide variety of housing](https://missingmiddlehousing.com/) are fun to walk around.

3) Neighborhoods like [Carroll Gardens](https://andreastrong.substack.com/p/so-long-williamsburg-carroll-gardens) or [Park Slope](https://www.planning.org/greatplaces/neighborhoods/2007/parkslope.htm), with [short commutes and medium density](https://marginalrevolution.com/marginalrevolution/2023/12/mr-commentator-sure-on-yimby.html), are lovely.

4) It would be fantastic for public health if most Americans had [compliant, safe, and dignified walking paths](https://www.strongtowns.org/journal/2023/7/28/if-we-want-a-shift-to-walking-we-need-to-prioritize-dignity) to a [third place](https://www.strongtowns.org/journal/2023/10/31/no-purchase-necessary) and a shopping center.

5. Our most productive regions --- the [San Francisco Bay](https://www.jpmorganchase.com/institute/research/cities-local-communities/institute-san-francisco-economy), [Dallas Fort-Worth](https://www.nbcdfw.com/news/local/dallas-fort-worth-leads-all-metro-areas-in-population-growth/3489168/), and the [Northeast megalopolis](https://www.bloomberg.com/news/articles/2019-02-28/mapping-the-mega-regions-powering-the-world-s-economy#:~:text=Bos%2DWash%2C,Kingdom%E2%80%99s%20or%20Brazil%E2%80%99s.) --- can all become clean, safe, and easy to get around. 