Sys.setenv(RETICULATE_MINICONDA_PATH = '~/miniconda3/')
options(blogdown.author = 'Seth Green', blogdown.ext = '.Rmd')
options(blogdown.initial_files.number = 0)
options(blogdown.knit.on_save = TRUE)
options(blogdown.hugo.version = "v0.119.0") 
