---
title: 'My milieu, childless Brooklyn '
author: Seth Green
date: '2024-09-12'
slug: my-milieu-childless-brooklyn
categories: []
tags: []
---

I have noticed recently that I seem to be part of a distinct demographic group without a name.

My friend Jacob and I came up with **Spunk**: Sporty Professional Urbanist, No Kids.

We are:

* Ages 30-45 
* Living in Brooklyn, SF, etc. 
* Thoroughly [professional managerial class](https://thebellows.org/the-double-horseshoe-theory-of-class-politics-the-bellows-2/) 
* Possessed of [omnivorous tastes](https://c-j-l-c.org/portfolio/omnivores-and-inequality-2/)
* Very physically active (running, [climbing](https://www.nytimes.com/2017/03/15/business/smallbusiness/rock-climbing-gyms-bouldering-walls.html), and hiking mostly)
* Readers (you can find us at [book bars](https://ny.eater.com/2024/8/14/24220327/bookstore-bars-new-york-lizs-book-bar-book-club-bar-bibliotheque-sullaluna))
* Joiners of [clubs](https://www.nytimes.com/2023/09/24/style/new-york-city-running-clubs.html) and [leagues](https://www.nytimes.com/2022/04/15/nyregion/ny-games.html)
* [Childless](https://www.nytimes.com/2024/07/25/well/mind/child-free-adults-pew-study.html) (maybe kids are on the long-term agenda, maybe not)
* Politically liberal but [market urbanists](https://x.com/CNLiberalism) on housing, public transport, and bike lanes 
* Reasonably successful at work but not workaholics
* Pretty good at our hobbies but not elite
* Without a singular dominant interest in our lives
* Occasionally experiencing the lifestyles of much richer people (e.g. when work flies us to Istanbul or Singapore to spend a week with colleagues)

There's a parallel to David Brooks's [Bobos in Paradise](https://archive.nytimes.com/www.nytimes.com/books/first/b/brooks-bobos.html) -- "These are highly educated folk who have one foot in the bohemian world of creativity and another foot in the bourgeois realm of ambition and worldly success. The members of the new information age elite are bourgeois bohemians" -- but I also want to capture our dedication to stakeless pursuits as a kind of rebuke to how everything in our childhoods had to have a point, an instrumental value. Meanwhile, our own lack of children, as my friend Rye puts it, "implies we are kind of spunky in a way that having no kids makes space for us to be." 

I wrote this at [Public Records](https://lampoonmagazine.com/article/2022/12/30/public-records-brooklyn/), which might as well be Spunk headquarters. 