---
title: The Pleasure of the Appendices of the Lord of the Rings
author: Seth Ariel Green
date: '2020-05-25'
tags:
  - fantasy-literature
  - lord-of-the-rings
slug: the-pleasure-of-the-appendices-of-the-lord-of-the-rings
---

In the foreword to the second edition of _The Lord of the Rings_, Tolkien writes:

> It is perhaps not possible in a long tale to please everybody at all points, nor to displease everybody at the same points; for I find from the letters that I have received that the passages or chapters that are to some a blemish are all by others specially approved.

Allow me to cast a vote of special approval for Appendices [A](http://tolkiengateway.net/wiki/Appendix_A) and [B](http://tolkiengateway.net/wiki/Appendix_B), particularly the sections about what the dwarves of the Lonely Mountain and the elves of the Woodland Realm and Lothlórien were doing during the [War of the Ring](https://lotr.fandom.com/wiki/War_of_the_Ring). These passages provide the all-too-rare pleasure, in literature and in life, of context.

_LOTR_ covers a lot of territory in multiple senses, but also just the [physical ground the characters cross](http://lotrproject.com/map/#zoom=3&lat=-1681.5&lon=1500&layers=BTTTTTTTT) to get from the Shire to Mount Doom. But in the climax, just about every main character converges on Mordor, either at its gate or its forge. The notable exceptions are the Elf-Lords introduced in _Fellowship_, and most of the main cast of _The Hobbit_ (and their descendants). We don't hear much from them after the Fellowship breaks apart, and asking "what was my personal favorite character doing during the big battle??" is the kind of thing that keeps fantasy readers up all night posting on (e.g.) [r/SwordOfTruth](https://www.reddit.com/r/SwordOfTruth/).

In the appendices, we learn that during the events of _Two Towers_ and _Return of the King_, Galadriel, Celeborn and the Galadhrim fend off three assaults on Lothlórien, while King Brand of the Dale and Dáin II Ironfoot fall in the [Battle of Dale](https://lotr.fandom.com/wiki/Battle_of_Dale), but delay Sauron's forces in the North enough for Aragorn's forces in the South to have something to return to after the [Battle of the Morannon](http://tolkiengateway.net/wiki/Battle_of_the_Morannon). As Gandalf says in _Appendix A: Annals of the Kings and Rulers, III: Durin's Folk_:

 > Think of what might have been. Dragon-fire and savage swords in Eriador, night in Rivendell. There might be no Queen in Gondor. We might now hope to return from the victory here only to ruin and ash.

By answering questions about broader events in Middle Earth that _only some readers might have_, in a supplement to the main text, Tolkien has simultaneously A) kept the central narrative streamlined for most readers; B) catered to his more obsessive fans' desire for completeness; and C) made the obsessive readers _work_ for it by parsing through timelines and lineages, which gives at least this reader a sense of accomplishment. The appendies also turn the second half of _The Hobbit_ -- everything after Bilbo wins the ring from Gollum -- into a marvelous plot payoff, because if not for the defeat of Smaug and the subsequent alliance of elves, dwarves, and men in the [Battle of Five Armies](https://lotr.fandom.com/wiki/Battle_of_Five_Armies), the North wouldn't have been unified, which would have allowed the forces of Dol Guldur to sweep down unopposed and lay ruin to Gondor. To quote Gandalf again, continuing from before:

> We might now hope to return from the victory here to ruin and ash. But that has been averted — because I met Thorin Oakenshield one evening on the edge of spring in Bree. A chance-meeting, as we say in Middle-earth.

Aha, you might think, reading this. So that's why _The Hobbit_ matters, and how it fits in. That's why Galadriel and Thranduil didn't send forces to aid in Rohan or Gondor (Peter Jackson undoes this by having [a squadron of Elvish archers](https://lotr.fandom.com/wiki/Haldir_(Lorien)#The_Lord_of_the_Rings_film_trilogy) show up in his adaptation of the Battle of Helm's Deep). And that's what happens to Dol Guldur after Sauron falls (Galadriel casts it down). Finally things make sense.

I wish I experienced this more in my life. Sometimes investigative journalism moves in this direction -- The _Times_ article on ['the lost month' of Coronavirus testing](https://www.nytimes.com/2020/03/28/us/testing-coronavirus-pandemic.html) is a little like this, except incomplete and infuriating. But Tolkien is a fantasy writer, and here the fantasy being spun is "there was a true story behind events, that coheres perfectly, and here it is." As a reader, as a person, this might be my truest, deepest desire: to know, to have the missing context. 

Back here in reality, context dies with people who never divulge it, or it never exists (there is no author, there is no one footnoting things with an eye to explaining). But to have it for a self-contained universe, to actually know -- that's what I love about the first two appendices of _The Lord of the Rings_.
