---
title: Date Me Docs, obviously
author: Seth Green
date: '2024-11-27'
slug: date-me-docs-obviously
categories: []
tags: []
---

I recently wrote a [date me doc](https://docs.google.com/document/d/1zyQGt7hMgV3iKj8vKlPMgS1ese2L3-ACGZixJAT0re0/edit?tab=t.0#heading=h.778fyscdi0hf) -- see [here](https://www.nytimes.com/2023/08/02/style/date-me-docs.html) for context. (I continue to be [belatedly zeitgeisty](https://setharielgreen.com/blog/i-ve-been-zeitgeisty-lately/).)

To me, the case that single people should do this is self-evident: why not? what are the costs? But a few pieces of social context made writing one seem not just desirable but advisable:

1.  Dating apps do not have our best interests in mind. They [constrain our self-presentations](https://www.nybooks.com/articles/2010/11/25/generation-why/?srsltid=AfmBOorbb1cblet88L1FKWm2wTV7h9ucUhXDrW1y06a-rrDeK_j4a7Op) to the prompts some PM figured would best [capture and monetize our attention](capture and monetize attention.).

2.  Finding a partner is important the way finding a job is important. It would be imprudent to rely entirely on LinkedIn in the job search. People typically prepare a CV, share it multiple places, take unsolicited emails form recruiters, etc. Surely we should be multimodal in our dating searches as well?

3.  Many single people I know wish to be set up by friends. But what would a friend say about me? I have no idea, and probably neither do they. Reducing me to a set of attributes, fixing it in one's mind, and repeating it is work. A date me doc is a way of helping our friends do that work.

4.  What is your comparative advantage on the dating market? If it is beauty, then Tinder might be a good fit. Mine sure isn't 😃

5.  Do you remember a time when trust was assumed? At beloved Swarthmore, I could strike up a conversation with just about anyone and assume they were an earnest, quirky nerd, and they could say the same of me. A format that allows that to shine through — or allows for people to inadvertently reveal that they are not who they think they are — helps establish that baseline trust again.
