---
title: Towards richly annotated digital books
author: Seth Green
date: '2024-01-16'
slug: richly-annotated-digital-books
categories: []
tags: []
---

I am reading _Lord of the Rings_ ([again](https://setharielgreen.com/blog/the-pleasure-of-the-appendices-of-the-lord-of-the-rings/)) and as always, there are many [words](https://setharielgreen.com/blog/all-the-words-in-lord-of-the-rings-that-i-did-not-know/)), phrases and names I don't know. But this time I am reading on my Kindle, so when Denethor talks about "Vorondil father of Mardil" who "hunted the wild kine of Araw in the far fields of Rhûnm," I can at least look up 'Vorondil' and cross-check his place in the appendix.

Even better would be an easy way to pull up and cross-check the [Tolkien Gateway](https://tolkiengateway.net/wiki/Main_Page), or the [Interactive Middle-Earth map](http://lotrproject.com/map/#zoom=3&lat=-1315.5&lon=1500&layers=BTTTTT), or perhaps Andy Serkis's off-kilter renditions of [Tom Bombadil's songs](https://www.reddit.com/r/lordoftherings/comments/pwgqjc/for_those_of_you_who_have_heard_them_does_andy/) in a way that allowed the reader to luxuriate in the details without losing their place in the text.

I suppose that copyright is one of the big reasons we don't have such projects. But if the creators of the [Dolphin emulator](https://en.wikipedia.org/wiki/Dolphin_(emulator)) or [Harmy's Despecialized Edition](https://en.wikipedia.org/wiki/Harmy%27s_Despecialized_Edition#Legality) can persist and even thrive in legal limbo, why not a book?

I suspect that there are some unsolved [UX problems](https://setharielgreen.com/blog/ux-testing-for-public-infrastructure/) here, and I think this could be a good project for someone who believes in the [transformative power](https://www.transformativeworks.org/) of derivative works.