---
title: Deleting social media creates (welcome) barriers to returning
author: Seth Green
date: '2024-03-06'
slug: no-more-infinity-scroll
categories: []
tags: []
---

Like [many people](https://www.honest-broker.com/p/how-to-break-free-from-dopamine-culture), I am troubled by my relationship with screens, particularly my phone's. I am trying three remedies. First, I use my phone in [grayscale, like Lorde](https://www.wmagazine.com/culture/lorde-internet-addiction-cure). Second, I avoid screens from [Friday sundown to Saturday sundown](https://en.wikipedia.org/wiki/Technology_Shabbat).[^1] Third, I deactivated my Facebook, and Instagram accounts, logged out of LinkedIn and Twitter, and deleted Reddit from my phone. For LinkedIn and Twitter, I deleted my passwords so I'd have to go through a recovery process to log in again.

Nothing radical here: we all recognize that [infinity scroll is bad for our brains](https://bootcamp.uxdesign.cc/how-the-invention-of-infinite-scrolling-turned-millions-to-addiction-3096602ef9af?gi=7bd25b366481). But today I'm noticing how social media companies have made it easier, once you've decided to log off, to *stay* off by making it [harder to browse](https://www.reddit.com/r/mobileweb/comments/f40xhi/this_has_to_be_a_joke_right_now_you_cant_access/) [when not](https://mashable.com/article/instagram-requires-log-in-to-view-profiles) [logged in](https://www.reddit.com/r/DataHoarder/comments/pa6dra/twitter_starts_to_require_login_to_view_tweets/). Scrolling becomes an ordeal, and an ordeal is a fine [commitment device](https://www.thebehavioralscientist.com/glossary/commitment-device). I actively want to be [kept out of the kingdom](https://www.theguardian.com/global/2021/aug/22/how-digital-media-turned-us-all-into-dopamine-addicts-and-what-we-can-do-to-break-the-cycle), like a compulsive gambler [self-excluding from a casino](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4016676/), and for whatever reason, the [dopamine cartel](https://www.honest-broker.com/p/the-state-of-the-culture-2024) helps by lowering the portcullis behind me.

I doubt a social planner would have designed things this way, but as a solution, it has the nice properties of being organic and voluntary.

[^1]: This has sometimes made making plans difficult, and I've been cheating to text and stuff; unfortunately once I pick up my phone, in my mind, all bets are off. What I really need is a dumb phone I can put my SIM card into on such occasions.
