---
title: I don't want to live in a world where light touch interventions reduce prejudice
author: Seth Green
date: '2021-11-27'
slug: i-don-t-want-to-live-in-a-world-where-light-touch-interventions-reduce-prejudice
draft: true
categories: [psychology]
tags: [meta-analysis]
---


A few years ago, I co-authored a meta-analysis of [contact hypothesis interventions](https://www.cambridge.org/core/journals/behavioural-public-policy/article/contact-hypothesis-reevaluated/142C913E7FA9E121277B29E994124EC5)^[for exapmle/exemplary papers, see Mousa ([2020](https://www.science.org/doi/abs/10.1126/science.abb3153)) or Scacco and Warren ([2018](https://www.cambridge.org/core/journals/american-political-science-review/article/abs/can-social-contact-reduce-prejudice-and-discrimination-evidence-from-a-field-experiment-in-nigeria/230FAEB8E4E9E756BF8560FE62E2FBAC)).] which was published online in 2018. Our paper differed from previous [contact](https://onlinelibrary.wiley.com/doi/abs/10.1002/ejsp.2079) [meta-analyses](https://psycnet.apa.org/record/2006-07099-004) in that, in addition to requiring actual face-to-face contact between members of different groups,[^%] we set two comparatively stringent inclusion rules: random assignment of treatment, and a delay between the onset of the intervention and outcome measurement of at least one day.[^*] By dint of these inclusion rules, most of the studies we looked at were, for lack of a better term, pretty psychologically intensive, e.g., a potentially [difficult conversation with a stranger](https://www.science.org/doi/10.1126/science.aad9713), or  six monthly meetings between Palestinian and Israeli high-school students in which they [discussed social issues and concluded with a joint trip to an amusement park](https://www.tandfonline.com/doi/abs/10.1080/17400201.2012.679253).

In 2020, I worked as a research assistant on a much [larger and more ambitious meta-analysis](https://doi.org/10.1146/annurev-psych-071620-030619), published in 2021, of _all_ studies with randomly assigned treatments intended to reduce prejudice from 2007 to 2019, across a wide range of theoretical perspectives. The overall meta-analytic effect the 2021 paper found was _d_ = 0.357, vs _d_ = 0.39 for our 2018 paper, so in some sense, both papers found that the studied interventions typically 'work' (by the measurements that authors choose). Both papers, however, find that more rigorous studies tend to find smaller results on average -- _prima facie_, evidence of [publication bias](https://arxiv.org/abs/physics/9909033) -- and both observe effect size heterogeneity between study categories. But the  difference between the papers that most interests me is the prevalence of so-called 'light touch' interventions in the 2021 paper's sample. The authors define a light-touch intervention as "easy to implement, brief, and cheap," e.g., "one in which participants were instructed to imagine how a fictional character felt as they watched a 3-minute film clip" ([Shih et al. 2013](https://psycnet.apa.org/record/2012-23868-001)); such studies comprise 76% of all studies in the sample, and the modal intervention "uses mentalizing as a salve for prejudice." 

Paluck et al. note a bunch of reasons why we should be skeptical that these interventions produce long-term effects, and the landmark studies they highlight are all comparatively heavyweight; though, as the authors note, many of them were undertaken by doctoral students, and  "frequently leveraged partnerships with existing organizations in order to conduct interventions at scale in settings with contentious intergroup relations. Moreover, they did so with high-dosage interventions
that played out over extended periods." The overall thrust here is that researchers should not be daunted by doing real-world, personally psychologically intensive, long-term interventions, because the potential upside is so great. 

Here's a different take: I fervently hope that these interventions don't work, because if they did, that would imply a truly frightening level of malleability of the human mind.

Consider Murrar and Brauer ([2017](https://journals.sagepub.com/doi/abs/10.1177/1368430216682350)), who run two experiments testing the effects of entertainment-education interventions. In the first, "White individuals ranging from 18 to 60 years of age" were randomly assigned to watch either six episodes of _Little Mosque on the Prairie_, which was written "to increase understanding of Western Muslims and the issues they face as a community," or six episodes of _Friends_, which, as the authors artfully put it, "exclusively depicts White characters going about their daily lives." In the second experiment, the treatment was to watch a 
"4-minute music video designed to reduce prejudice towards Muslims" in which "diverse Muslim Americans... enjoy activities typical Americans do (e.g., watching TV), admire popular icons (e.g., Justin Timberlake), do kind things (e.g., write inspirational messages on dollar bills), recognize their flaws (e.g., admit to being annoyed by their parents sometimes), and have admirable life goals (e.g., changing the world)." The authors find positive results across a variety of measures and conclude that the studies "provide strong evidence for the effectiveness of entertainment-education at reducing prejudice." The authors note that the positive effects of watching _Little Mosque_ persist at the 4 week mark.

Let's think about this for a minute. 

* Mulak and Winiewski ([2021](https://cyberpsychology.eu/article/viewFile/13117/12379)) study the effects of representations of diversity within videogames. They recruited gamers via "posts on three largest polish Facebook groups for gamers" and surveyed them on their video game habits and their prejudical attitudes towards "Jews, Roma, Eastern Europeans, Asians, Black people and Muslims." They then had two judges independently code the 44 most popular games in the survey for how how often they depict members of "real-world" minority groups, as well as contact with "fictional races", and then also code how positive or negative that contact was on a 1-7 scale. Overall, the authors find, "average quality of contact with minorities in a game (measured at game-level, as a characteristic of a game) was associated with higher acceptance of minorities of the players (measured at individual level)," while "[d]iversity of the
game world generated by fictional races had no significant connection to attitudes." (And yes, I know this is more of a 'no-touch' study rather than a light-touch intervention because it surveys people on their extant behaviors; but I think the general point I'm trying to get at is illustrated well.) Another interesting tidbit from the study is that the average participant spent "25.92 hours per week playing games." 

[^%]: As opposed to, e.g., Fuegen ([2000](https://elibrary.ru/item.asp?id=5290507)), who had actors pretend to be stereotypical feminists or not.

[^*]: Pettigrew later argued that our paper

    > set an unrealistically high bar for contact studies to warrant application...We can all agree that rigorous experimental work on contact effects would be ideal to have in greater abundance. But for practical reasons of finances and opportunity, we know why such research is relatively rare in the discipline—especially in field research that is the mainstay of contact work. By the stringent standards put forth by Paluck et al. (2019), only limited areas in social psychology would deserve application.