---
title: Four observations about "The Substance"
author: Seth Green
date: '2024-09-25'
slug: four-observations-about-the-substance
categories: []
tags: []
---

1.  I would have enjoyed this movie a bit more with some tighter editing, less repetition, and more leavening humor. But I did enjoy it. [Diana Stevens](https://slate.com/culture/2024/09/the-substance-demi-moore-movie-margaret-qualley.html), who shares some of my concerns, didn't.

2.  This movie is basically Fight Club with no good/bad distinction between the halves of the self. (Although Fight Club is also a little confused about this because it's so horny for Brad Pitt.) [Sarah Gorr](https://thespool.net/reviews/movies/film-review-the-substance-2024-mubi-demi-moore-margaret-qualley/) makes the same connection.

3.  I am not so keen on movies that try have their cake and eat it too. "The Substance" wants to satirize and make grotesque our society's obsession with young women's bodies while also featuring about 200 slow-motion shots of Margaret Qualley's ass. I found this juxtaposition a little hard to process. So did [Rhonda Garelick](https://www.nytimes.com/by/rhonda-garelick).

4.  I liked the the Elizabeth-making-food scene because it makes the connection between borrowing-the-flesh-of-another-to-stay-young and eating meat explicit. Blood sausage is literally vampiric. I have not seen this connection pointed out elsewhere yet.

Here is my [Letterboxd review](https://letterboxd.com/setgree/film/the-substance/).
