---
title: The fraud is the lack of use cases
author: Seth Green
date: '2023-10-30'
slug: the-fraud-is-the-lack-of-use-cases
categories: []
tags: []
---



<p>I have been consuming a lot of SBF content lately, e.g. Zvi Mowshowtiz’s <a href="https://thezvi.substack.com/p/book-review-going-infinite">review of <em>Going Infinite</em></a>, David Morris’s <a href="https://davidzmorris.substack.com/p/profiles-in-corruption-dan-friedberg">comments on</a> FTX’s lawyer, Molly White’s <a href="https://newsletter.mollywhite.net/p/the-ftx-trial-day-thirteen-sam-bankman">courtroom reporting</a>, and a <a href="https://www.bloomberg.com/features/2023-ruin-ftx-documentary/">Bloomberg documentary</a>.</p>
<p>To summarize the story so far:</p>
<ol style="list-style-type: decimal">
<li>someone(s) working at FTX and/or Alameda <a href="(https://protos.com/alameda-research-used-customer-funds-as-early-as-2019-gary-wang-testifies/)">set things up</a> to allow Alameda to gamble with FTX customer money.</li>
<li>Alameda more or less burned that money on a bunch bets that <a href="https://nymag.com/intelligencer/article/zeke-faux-number-go-up-book-excerpt.html">Number Go Up</a>, AKA that the crypto market would grow monotonically.</li>
<li>That turned out to be <a href="https://www.fxstreet.com/cryptocurrencies/news/alameda-researchs-balance-history-on-ftx-confirms-death-blow-happened-during-luna-collapse-expert-says-202309120314">false</a>.</li>
<li>Eventually, people <a href="https://www.coindesk.com/business/2022/11/02/divisions-in-sam-bankman-frieds-crypto-empire-blur-on-his-trading-titan-alamedas-balance-sheet/">found out</a> that a lot of Alameda’s extant assets were just FTX-brand <a href="https://www.bloomberg.com/news/articles/2022-04-25/sam-bankman-fried-described-yield-farming-and-left-matt-levine-stunned">magic beans</a> with no real value.</li>
<li>FTX depositors <a href="https://www.cato.org/blog/bank-crypto-runs-factx-vs-fiction">got scared</a> (or <a href="https://cointelegraph.com/news/changpeng-zhao-tweet-ftx-collapse-caroline-ellison">were spooked</a>) and tried to withdraw their money, on the theory that trouble at one company meant trouble at the other.</li>
<li>This theory turned out to be sound, and FTX <a href="https://www.coindesk.com/business/2022/11/08/ftx-exchange-halts-all-crypto-withdrawals/">couldn’t meet withdrawals</a>, in <a href="https://www.coindesk.com/policy/2022/11/10/ftx-violated-its-own-terms-of-service-and-misused-user-funds-lawyers-say/">violation of its terms of service</a>.</li>
<li>After more machinations, FTX <a href="https://www.nytimes.com/2022/11/11/business/ftx-bankruptcy.html">declared bankruptcy</a>, and now Sam Bankman-Fried is <a href="https://www.coindesk.com/policy/2023/10/30/live-sam-bankman-fried-takes-the-stand-for-a-third-day-in-ftx-fraud-trial/">taking the stand in New York</a>.</li>
</ol>
<p>As best I can tell, his defense strategy is to <a href="https://twitter.com/innercitypress/status/1719139120818037125">dispute who authorized step 1</a>, the loaning of FTX assets to Alameda. SBF is basically claiming that someone else at the company set this up, and he wasn’t aware of it, that he was just following the advice of his lawyer. This is, on the face of it, preposterous, but also I don’t see how it’s exculpatory. Judge Kaplan <a href="https://www.businessinsider.com/judge-blasts-sam-bankman-fried-testimony-answers-ftx-customer-funds-2023-10">shares my skepticism</a>.</p>
<p>But taking a step back here, I also think that step 2 is fraudulent. The two ways for a market to grow in value indefinitely, theoretically, are to create economic growth or to capture market share from incumbents. If you’re not doing one of those two things, but the number is still going up, it’s probably a ponzi scheme. SBF explicitly endorsed the idea that <a href="https://news.ycombinator.com/item?id=33594284z">yield farming was a ponzi</a>, and FTX existed to facilitate these ponzis and take a small cut every time someone bought in. This was, apparently, a <a href="https://blockworks.co/newsletter/issue/32986077#:~:text=On%20why%20it%20happened%3A%20%E2%80%9CI%20know%20how%20much%20real%20revenue%20we%20were%20making%3A%20two%20bips%20%5B0.02%20percent%5D%20on%20two%20hundred%20fifty%20billion%20dollars%20a%20month%2C%E2%80%9D%20said%20Zane%20%5BTackett%5D.%20%E2%80%9CI%E2%80%99m%20like%2C%20Dude%2C%20you%20were%20sitting%20on%20a%20fucking%20printing%20press%3A%20why%20did%20you%20need%20to%20do%20this%3F%E2%80%9D">very profitable business</a>, but you could argue that they weren’t <em>directly</em> propping up, or gambling on, those ponzis.</p>
<p>But Alameda basically was. We now know it lost <a href="https://watcher.guru/news/bankman-fried-terrausd-led-to-100m-in-losses-for-alameda">$100 million in the Terra/Luna collapse</a>, which was an <a href="https://www.theverge.com/2022/5/20/23131647/terra-luna-do-kwon-stablecoin-anchor">obvious ponzi</a>. They lost another $190 million due to <a href="https://cryptorank.io/news/feed/7dcf5-the-alameda-research-and-ftx-debacle-uncovering-the-truth">poor security practices</a> on assets that weren’t really worth anything in the first place. From <a href="https://www.theverge.com/2023/10/11/23913665/ftx-sam-bankman-fried-fraud-trial-caroline-ellison-testimony-alameda-balance-sheets">what we know of their balance sheet</a>, at no point were they investing in any kind of crypto play with even a remote shot of competing economically on its own terms, or of creating new opportunities for growth.</p>
<p>On twitter, Alameda leadership boasted that their ability to time the market was <a href="https://twitter.com/AlamedaTrabucco/status/1385181088029450243">effectively a superpower</a>. But this was all, obviously, going to pop unless someone, somewhere, figured out something to actually <em>do</em> with crypto that couldn’t be done before.<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a> If you didn’t have that, then you were knowingly trying to profit from other people’s financial naivete. That is a bad, unethical thing to do.</p>
<p>To me, that lack of curiosity about use cases is at the heart of what went wrong at Alameda, and crypto in general.<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a></p>
<div class="footnotes footnotes-end-of-document">
<hr />
<ol>
<li id="fn1"><p>Buying drugs on the internet is a fine use case, but its total addressable market is nowhere near as large as crypto’s peak valuation.<a href="#fnref1" class="footnote-back">↩︎</a></p></li>
<li id="fn2"><p>But then, as <a href="https://travellingthroughwords.com/index.php/2017/02/25/quotes-of-the-week-9-harry-potter-and-the-deathly-hallows-by-j-k-rowling/#:~:text=But%20then%2C%20if%20he%20had%20been%20able%20to%20understand%2C%20he%20could%20not%20be%20Lord%20Voldemort%2C%20and%20might%20never%20have%20murdered%20at%20all">Dumbledore says about Voldemort</a>: if they had been capable of that kind of introspection, then they woulnd’t have been Alameda in the first place.<a href="#fnref2" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
