---
title: The fraud is the lack of use cases
author: Seth Green
date: '2023-10-30'
slug: the-fraud-is-the-lack-of-use-cases
categories: []
tags: []
---

I have been consuming a lot of SBF content lately, e.g. Zvi Mowshowtiz's [review of _Going Infinite_](https://thezvi.substack.com/p/book-review-going-infinite), David Morris's [comments on](https://davidzmorris.substack.com/p/profiles-in-corruption-dan-friedberg) FTX's lawyer, Molly White's [courtroom reporting](https://newsletter.mollywhite.net/p/the-ftx-trial-day-thirteen-sam-bankman), and a Bloomberg's documentary called ['Ruin'](https://www.bloomberg.com/features/2023-ruin-ftx-documentary/).

To summarize the story so far: 

  1. someone(s) working at FTX and/or Alameda [set things up]((https://protos.com/alameda-research-used-customer-funds-as-early-as-2019-gary-wang-testifies/)) to allow Alameda to gamble with FTX customer money.
  2. Alameda  more or less burned that money on a bunch  bets that [Number Go Up](https://nymag.com/intelligencer/article/zeke-faux-number-go-up-book-excerpt.html), AKA that the crypto market would grow monotonically. 
  3. That turned out to be [false](https://www.fxstreet.com/cryptocurrencies/news/alameda-researchs-balance-history-on-ftx-confirms-death-blow-happened-during-luna-collapse-expert-says-202309120314). 
  4. Eventually, people people [found out](https://www.coindesk.com/business/2022/11/02/divisions-in-sam-bankman-frieds-crypto-empire-blur-on-his-trading-titan-alamedas-balance-sheet/) that a lot of Alameda's extant assets were just FTX-brand [magic beans](https://www.bloomberg.com/news/articles/2022-04-25/sam-bankman-fried-described-yield-farming-and-left-matt-levine-stunned) with no real value.
  5. FTX depositors [got scared](https://www.cato.org/blog/bank-crypto-runs-factx-vs-fiction) (or [were spooked](https://cointelegraph.com/news/changpeng-zhao-tweet-ftx-collapse-caroline-ellison)) and tried to withdraw their money, on the theory that trouble at one company meant trouble at the other.
  6. This theory turned out to be sound, and FTX [couldn't meet withdrawals](https://www.coindesk.com/business/2022/11/08/ftx-exchange-halts-all-crypto-withdrawals/), in  [violation of its terms of service](https://www.coindesk.com/policy/2022/11/10/ftx-violated-its-own-terms-of-service-and-misused-user-funds-lawyers-say/).
  7. After more machinations, FTX [declared bankruptcy](https://www.nytimes.com/2022/11/11/business/ftx-bankruptcy.html), and now Sam Bankman-Fried is [taking the stand in New York](https://www.coindesk.com/policy/2023/10/30/live-sam-bankman-fried-takes-the-stand-for-a-third-day-in-ftx-fraud-trial/). 
  
As best I can tell, his defense strategy is to [dispute who authorized step 1](https://twitter.com/innercitypress/status/1719139120818037125), the loaning of FTX assets to Alameda. SBF is basically claiming that someone else at the company set this up, and he wasn't aware of it, that he was just following the advice of his lawyer. This is, on the face of it, preposterous, but also I don't see how it's exculpatory. Judge Kaplan [shares my skepticism](https://www.businessinsider.com/judge-blasts-sam-bankman-fried-testimony-answers-ftx-customer-funds-2023-10).

But taking a step back here, I also think that step 2 is fraudulent. The two ways for a market to grow in value indefinitely, theoretically, are to create economic growth or to capture market share from incumbents. If you're not doing one of those two things, but the number is still going up, it's probably a ponzi scheme. SBF told Matt Levine explicitly that that's how he should think about [yield farming](https://news.ycombinator.com/item?id=33594284) yield farming, which FTX was _profiting from_ without really doing.^[instead it was taking a small cut of every transaction where _other_ people tried to get rich from these magic beans. This was apparently [a very good business](https://blockworks.co/newsletter/issue/32986077#:~:text=On%20why%20it%20happened%3A%20%E2%80%9CI%20know%20how%20much%20real%20revenue%20we%20were%20making%3A%20two%20bips%20%5B0.02%20percent%5D%20on%20two%20hundred%20fifty%20billion%20dollars%20a%20month%2C%E2%80%9D%20said%20Zane%20%5BTackett%5D.%20%E2%80%9CI%E2%80%99m%20like%2C%20Dude%2C%20you%20were%20sitting%20on%20a%20fucking%20printing%20press%3A%20why%20did%20you%20need%20to%20do%20this%3F%E2%80%9D).]

But Alameda was. Apparently it lost [$100 million in the Terra/Luna collapse](https://watcher.guru/news/bankman-fried-terrausd-led-to-100m-in-losses-for-alameda), which was an [obvious ponzi](https://www.theverge.com/2022/5/20/23131647/terra-luna-do-kwon-stablecoin-anchor). Apparently they lost another $50 million due to [poor security practices](https://cryptorank.io/news/feed/7dcf5-the-alameda-research-and-ftx-debacle-uncovering-the-truth). From [what we know of their balance sheet](https://www.theverge.com/2023/10/11/23913665/ftx-sam-bankman-fried-fraud-trial-caroline-ellison-testimony-alameda-balance-sheets), at no point were they investing in any kind of crypto play with even a remote shot of competing economically on its own terms, or of creating new opportunities for growth. 

On twitter, Alameda leadership boasted that their ability to time the market was [effectively a superpower](https://twitter.com/AlamedaTrabucco/status/1385181088029450243). But this was all, obviously, going to pop unless someone, somewhere, figured out something to actually _do_ with crypto that couldn't be done before.^[Buying drugs on the internet is a fine use case but its maximum possible size is nowhere near enough to justify bull market valuations.] If you didn't have that, then you were knowingly trying to profit from other people's financial naivete That is a bad, unethical thing to do. 

To me, that lack of curiosity about use cases is at the heart of what went wrong at Alameda, and crypto in general.^[But then, as [Dumbledore says about Voldemort](https://travellingthroughwords.com/index.php/2017/02/25/quotes-of-the-week-9-harry-potter-and-the-deathly-hallows-by-j-k-rowling/#:~:text=But%20then%2C%20if%20he%20had%20been%20able%20to%20understand%2C%20he%20could%20not%20be%20Lord%20Voldemort%2C%20and%20might%20never%20have%20murdered%20at%20all): if they had been capable of that kind of introspection, then they woulnd't have been Alameda in the first place.]