---
title: Five observations about "The Substance"
author: Seth Green
date: '2024-09-25'
slug: five-observations-about-the-substance
categories: []
tags: []
---

1.  I would have enjoyed this movie a bit more with some tighter editing, less repetition, and more leavening humor. But I did enjoy it. [Diana Stevens](https://slate.com/culture/2024/09/the-substance-demi-moore-movie-margaret-qualley.html), who shares some of my concerns, didn't.

2.  This movie is basically Fight Club with no good/bad distinction between the halves of the self. (Although Fight Club is also a little confused about this because it's so horny for Brad Pitt.) [Sarah Gorr](https://thespool.net/reviews/movies/film-review-the-substance-2024-mubi-demi-moore-margaret-qualley/) makes the same connection.

3.  Fargeat seems to want both to punish Demi Moore, and by extension the audience, for idolizing young women's bodies, and then to spend about an hour oggling Margaret Qualley. I found this a little hard to process. So did [Rhonda Garelick](https://www.nytimes.com/2024/09/23/style/getting-old-never-looked-so-ugly.html). On the other hand, [scolds are often titillated by the thing that offends them](https://hazlitt.net/feature/reefer-madness-real).

4.  I liked the the Elizabeth-making-food scene because it makes the connection between borrowing-the-flesh-of-another-to-stay-young and eating meat explicit. Blood sausage is literally vampiric. I have not seen this connection pointed out elsewhere. [Mayukh Sen](https://www.eater.com/24252233/the-substance-demi-moore-food-movie) also enjoyed the movie's treatment of food.

5.  This movie should have ended with a **RAMPAGE!!** The final application of the serum could have morphed some kind of super beast with claws and fangs who drank men's spinal fluid to stay alive. Tarantino, whose films often annoy me, wouldn't have missed this opportunity.

Here is my [Letterboxd review](https://letterboxd.com/setgree/film/the-substance/).
