---
title: '''Someone to sit in your chair/To ruin your sleep'''
author: Seth Green
date: '2024-04-02'
slug: being-alive
categories: []
tags: []
---

Some thoughts.

* In [_Being Alive_](https://genius.com/Original-broadway-cast-of-company-being-alive-lyrics), Bobby enumerates deep and shallow reasons to stay single. Paul responds: there's more than that. He's right, but I also think: those things are important because they're true, because they're real.

* "[A person like Bob doesn’t have the good things](https://genius.com/Original-broadway-cast-of-company-side-by-side-by-side-what-would-we-do-without-you-lyrics) and he doesn’t have the bad things,  but he doesn’t have the good things," I get it. 

* On _Adventure Time_, [Prismo says](https://www.youtube.com/watch?v=HZNYlvbUDcc): "when I’m alone I can just sit on the couch and when I’m hungry I can eat whatever I want. It’s not like: 'What should we eat for breakfast? Wait! We should coordinate!'" Jake calls this bleak, but I think I would instead call it injured.

* Jia Tolentino writes, in [_Ecstasy_](https://www.newyorker.com/magazine/2019/05/27/losing-religion-and-finding-ecstasy-in-houston), that MDMA can "make you feel like the best version of the person you would be if you were able to let your lifelong psychological burdens go."I would like to find this again, but not in a way that just allocates a week’s worth of dopamine into a single day. But that person who let their burdens go would not be bothered by coordinating about breakfast. 

* During the pandemic I wrote in my diary that incessant Zoom calls were [fake plastic trees](https://www.youtube.com/watch?v=n5h0qHwNrHk): "It wears you out. it wears you out." Today I rue how normal it has become, for children and adults, to spend a whole day alone in one's bedroom, looking at screens. I dread the incoming future of AI content on VR goggles. 

* I observe that religious institutions have [prebuilt rules and norms](https://www.lesswrong.com/posts/p7hW7E3fHF3PDzErk/sabbath-hard-and-go-home) around limiting phone use. Everyone else has to make it up.

* As [the wraith](https://ambiguities.wordpress.com/2008/11/02/the-wraith/) in _Infinite Jest_ says: "No! No! _Any_ conversation or interchange is better than none at all, to trust him on this, that the worst kind of gutwrenching intergenerational interface is better than withdrawal or hiddenness on either side."

* Robert Frost [writes](https://www.poetryverse.com/robert-frost-poems/a-servant-to-servants) that "the best way out is always through." For me, that means more communalism. More putting up with people who sit in my chair, who listen to their music without headphones, who ruin my sleep, and loving those inconveniences because they mean I am alive. 

