---
title: What if college sports were focused on public health?
author: Seth Green
date: '2024-03-19'
slug: what-if-college-sports-were-focused-on-public-health
---

In college I played chamber music and ran track and cross country (XC). While both were subsidized by the school, playing music has positive spillovers both for the community (people got to see our concerts) and into the future (e.g. something about how a meaningful life involves making art). Track & XC had, to a first approximation, zero positive benefits for the community at large. (Track meets are boring and XC meets are boring _and_ far away.) Any justification of the sport as a college-sanctioned activity for some but not all people has to start with enrichment for participants.

It's plausible that [team sports build valuable skills](https://www.bloomberg.com/opinion/articles/2023-10-14/sports-are-part-of-the-college-curriculum-too) that translate to higher salaries and bigger donations to colleges. Maybe that's true for some sports, but  I find it hard to believe for runners. Moreover, if that were true, you'd want to make sports as accessible as possible, i.e. move to club sports models and much larger teams.

Second, it could be about instilling lifelong healthy habits. Personally I'm grateful to have learned how to run fast, lift, structure workouts, etc. I'd say I got my money's worth from participating.  But I also notice that most of my teammates don't run anymore. 

Life happens and interests shift, I get it. But I also blame college athletics, like so many activities for children and adolescents, for turning games of pleasure into contests for status, which are addictive but ultimately unfulfilling.

People on my team took running, and their roles as student athletes, very seriously. Maybe that makes sense at some places where the teams are really good, but this was Swarthmore: no one cared how we ran. _I_ barely cared. But competitive running brings stress, [disordered eating](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6377974/), and [overuse injuries](https://scholar.harvard.edu/files/dlieberman/files/2012c.pdf). It also facilitates burnout. Ten years later, by and large, college athletes give it up. My running groups are mostly filled with people who didn't run in college or high school.

Observation: running clubs have become, post-pandemic, both [very popular](https://www.nytimes.com/2023/09/24/style/new-york-city-running-clubs.html) and very Instagramified. If I go on five structured runs a week, four begin with a group photo destined for social media. I've been running ~4-6 days a week for almost 20 years now, so I don't personally get much out of this, but clearly some people do! As a running friend recently put it, "think of it as a public health strategy. Anything that gets people moving is good." 

Extending this logic back to college athletics: how would things be different if their whole point was public health, e.g. fitness, community, time outside? 

* They'd be available to everybody. Maybe games/competitions/meets might have qualifiers but group practices and workouts would be open. 

* They'd put on exhibition matches/fun runs regularly. 

* They'd raise money for charities. 

* Coaches could be part-time or volunteers. 

* Colleges could stop recruiting (perhaps a few strong Division I programs could still nurture future Olympians) and cut down athletic staff to the bare minimum (e.g. to schedule field time, though a student volunteer group could probably handle it).

* Participants could pay their own way or fund-raise for away games. 

In other words, they would just become athletic clubs. 

Overall I think this would be a better model for college athletics than the one we have, and more of my teammates, I think, would still be running.