---
title: Rihanna & Borges; or, when Rihanna covers "Same Ol' Mistakes,"
author: Seth Green
date: '2020-07-09'
slug: rihanna-borges-or-when-rihanna-covers-same-ol-mistakes
---

she imparts to the text the full weight of her celebrity. The words

> Finally taking flight  
I know you don't think it's right  
I know that you think it's fake  
Maybe fake's what I like

become rich with the overtones of her many personas: [badgirlriri](https://www.instagram.com/badgalriri/?hl=en), the [world's richest woman musician](https://www.cnn.com/2019/06/05/entertainment/rihanna-wealth-scli-intl/index.html), the CEO of a [huge corporation](https://en.wikipedia.org/wiki/Fenty_Beauty) -- a person who has lived half her life under unbearable scrutiny, here, acknowledging the burden of making art that appeals to the median human. When [Kevin Parker](https://en.wikipedia.org/wiki/Kevin_Parker_(musician)) sings the same words, he speaks to a smaller niche, defending himself against accusations of selling out for achieving a tiny fraction of the fame Rihanna lives with. 

That the text bears the author's intent, but also the state of the speaker -- these two versions, these two songs, drive that home particularly well because (as far as I can tell) literally nothing besides the vocals is different between them.

Cf. Borges's _Pierre Menard, Author of Don Quixote_, a story about a man who endeavors to write something

> subterranean, interminably heroic, and unequalled and which is also -- oh,  the possibilities inherent in the man! -- inconclusive. This work, possibly the most significant of our time, consists of the ninth and thirty-eighth chapters of Part One of _Don Quixote_ and a fragment of the twenty-second chapter...  
He did not want to compose another _Don Quixote_ -- which would be easy -- but _the Don Quixote_. It is unnecessary to add that his aim was never to produce a mechanical transcription of the original; he did not propose to copy it. His admirable ambition was to produce pages which would coincide -- word for word and line for line -- with those of Miguel de Cervantes.

When I hear Rihanna's "Same Ol' Mistakes," I hear just this: a song that coincides "word for word and line for line" with Tame Impala's song of the same name, and means something entirely different. 

Of particular interest, a passage in _Pierre Menard_ comparing a line from the two *Don Quixote*s:

> | The text of Cervantes and that of Menard are verbally identical, but the second is almost infinitely richer. (More ambiguous, his detractors will say; but that ambiguity is a richness.) It is a revelation to compare the _Don Quixote_ of Menard with that of Cervantes. The latter, for instance, wrote (_Don Quixote_, Part One, Chapter Nine):  
> > |     [...truth, whose mother is history, who is the rival of time, depository of deeds, witness of the past, example and lesson to the present, and warning to the future.]

> | Written in the seventeenth century, written by the "ingenious layman" Cervantes, this enumeration is a mere rhetorical eulogy of history. Menard, on the other hand, writes:  
> > |     [...truth, whose mother is history, who is the rival of time, depository of deeds, witness of the past, example and lesson to the present, and warning to the future.]

> | History, _mother_ of truth; this idea is astounding. Menard, a contemporary of William James, does not define history as an investigation of reality, but as its origin...Equally vivid is the contrast in styles. The archaic style of Menard -- in the last analysis, a foreigner -- suffers from a certain affectation. Not so that of his precursor, who handles easily the ordinary Spanish of his time.

I wonder what Rihanna would make of this? 

For what it's worth, Borges's next sentence, I part ways with:

> There is no intellectual exercise which is not ultimately useless. 

I don't know, I had fun thinking about this. Is that not a kind of use?
