---
title: Despicableness as Context
author: Seth Green
date: '2020-07-30'
slug: despicableness-as-context
categories: []
tags: []
---

I would like to figure out when and how to engage with artists who are bad people.

On the one hand, Richard Wagner did not much care for Jews -- and not just in the way that was cant for 19th century Germans, but actively going out of his way to [disparage Jews and Jewish composers](https://en.wikipedia.org/wiki/Das_Judenthum_in_der_Musik).[^wagner] This doesn't bother me, and I think it's because I don't see any connection between his music and his beliefs. _Ride of the Valkyries_ works as a statement of grandeur and violence [wherever it pops up](https://www.youtube.com/watch?v=30QzJKCUekQ). 

But when R. Kelly sings

> My mind's tellin' me no, but my body, my body's tellin' me yes

it reads like a defense of [his horrible behavior](https://en.wikipedia.org/wiki/Surviving_R._Kelly); the context of his despicableness suffuses the text. When you cue that song up on Youtube, in a tiny way, you're literally buying his defense. That's a very different stance for a listener. For me, it's untenable.

Cf. Michael Jackson, whose music is much creepier than I remember it being as a kid[^mj] (my friend Roger suggested these snippets):

> You've been hit by/You've been hit by/A smooth criminal

> And no one's gonna save you/From the beast about to strike

Other obvious examples: Woody Allen has a (formerly) critically-acclaimed movie [featuring himself dating a teenager](https://nexttribe.com/woody-allens-manhattan/), the very title of Louis CK's [movie](https://en.wikipedia.org/wiki/I_Love_You,_Daddy) seems like the expression of a horrible man's fantasies _and_ it features an [extended pantomimed masturbation scene played for laughs](https://www.vulture.com/2017/11/the-uncomfortable-masturbation-scene-in-louis-c-k-s-movie.html) -- there is _no line here_ between context and text for these men and their products. My intuition is that when this [legion of horribles](https://www.goodreads.com/quotes/328033-a-legion-of-horribles-hundreds-in-number-half-naked-or), this [basket of deplorables](https://en.wikipedia.org/wiki/Basket_of_deplorables), makes art, the presumption should be that it is intended as a defense of (or distraction from[^cosby]) their despicableness, and consuming it is an act of endorsement, or at least of suggesting an open mind to their apologias. 

Is the relevant distinction that we can look past artists' believing hateful things, but not their terrible behavior? I don't think so. First, the distinction is likely to be pretty thin, because we can safely presume that people who believe horrible things are more likely to _do_ horrible things, even if we don't hear about them. Second, this doesn't seem to reliably guide whose work I (or we) choose to disengage from. 

Consider Picasso, whose [sharp angles and misplaced bodyparts](https://www.anothermag.com/art-photography/8799/the-women-behind-the-work-picasso-and-his-muses) render his woman subjects ghastly, grotesque, visually dehumanized. So yes, the context of his being [famously awful to women in his life](https://www.theparisreview.org/blog/2017/11/09/how-picasso-bled-the-women-in-his-life-for-art/) matters. Shall I boycott Picasso, and the museums that host his work? I am not ready to do so,[^met]: but I don't have a good reason why I shouldn't. One thing that occurs is that he's already dead, so it's not like I'm benefiting the abuser. But I don't see why that should matter.

Some less highfalutin examples: Apparently TJ Miller [actually _is_](https://en.wikipedia.org/wiki/T.J._Miller#Legal_issues_and_controversies)  [Erlich Bachman](https://silicon-valley.fandom.com/wiki/Erlich_Bachman), and his performance on _Silicon Valley_ is (to me) an all-time great embodiment of male cluelessness. Is it unethical to pay him for playing a horrible man on TV, if the excellence of his performance stems from his being one in real life?[^franzen] Ditto for Aziz Ansari's apparently being just as creepy as [Tom Haverford](https://en.wikipedia.org/wiki/Tom_Haverford) is on _Parks and Recreation_ -- his character is one of my least favorite things about a show I like, but it's not as though, when I'm watching, I can make micropayments during scenes I like to signal that I think Amy Poehler's performance is Emmy-worthy and they should write Tom off the show.[^micropayments]

Insofar as I spend many hours a week engaging with art (broadly defined to include TV, books, videogames,[^videogame] etc.), the question of what art to engage with and why is important. I can think of examples that are clearly "no," where the context and the text are patently isomorphic (Woody Allen, Louis CK), as well as cases that are clearly "I don't care" (Wagner, [Alice Walker](https://en.wikipedia.org/wiki/Alice_Walker#Accusations_of_antisemitism), [Public Enemy](https://genius.com/14074)).[^pe] 

But for cases in between these extremes, I more or less seem to decide based on whether I feel disgust when I engage with the material, which does not seem to be a very reliable basis for good moral decisions.  

I am not sure what else to do, but if I come up with a better answer, I'll let you know. 

[^wagner]: I think that we _remember_ Wagner as especially antisemitic not because of his beliefs but because he was one of [Hitler's favorite composers](https://en.wikipedia.org/wiki/Wagner_controversies#Nazi_appropriation).

[^mj]: In retrospect, _of course_ his music is slick and seductive towards children, of course I would not understand that the man holding this sonic candy out wanted to hurt me.

[^cosby]: There they are, miming an upstanding man [on TV](https://en.wikipedia.org/wiki/The_Cosby_Show) or in [a book on modern dating](https://www.nytimes.com/2015/07/07/books/review-aziz-ansaris-modern-romance-explores-dating-in-the-digital-age.html). 

[^franzen]: Jonathan Franzen's [essay of rememberance for his friend David Foster Wallace](https://www.newyorker.com/magazine/2011/04/18/farther-away-jonathan-franzen) "pass[es] over...the question of how such a beautiful human being had come by such vividly intimate knowledge of the thoughts of hideous men," which in turn passes over the question of what it was like for Franzen to maintain decades of friendship with an [obvious](https://www.nytimes.com/2020/02/11/books/review/in-the-land-of-men-adrienne-miller.html) [misogynist](https://lareviewofbooks.org/article/david-foster-wallace-in-the-metoo-era-a-conversation-with-clare-hayes-brady/).

[^micropayments]: This feels like a plausible development for TV in my lifetime, though.

[^videogame]: In case you're curious, I follow the _Wired Magazine_ convention here of making [videogame one word](https://www.wired.com/2007/11/on-videogame-ve/) (I  looked this up when Rstudio threw a spelling error).

[^pe]: In light of these being the examples that came to mind, I think that I might just not care very much about antisemitism. It doesn't feel like an active threat. I see Alice Walker as being very misguided on the question of Jews' influence, and I hope that someone steers her right.