---
title: The magic of Steve Reich's music is that I can process it
author: Seth Green
date: '2020-08-16'
slug: The magic of Steve Reich's music is that I can process it
---

I would like to be able to hear and reproduce every note of the introduction to [Nausicaä of the Valley of the Wind](https://open.spotify.com/track/0QW4RCyj2Tc2N0hD1FjkcS?si=imNv5LlsQuq2-F7ULjsxTA), but it is too dense. For other, simpler parts of the soundtrack, you can find [Youtube videos](https://www.youtube.com/watch?v=NdVl5Yc4_mo) that display all pitches, their duration, and their position on a keyboard. I could more or less transcribe the same portions of the score onto a musical staff by ear, but I can't do this for the introduction, because simultaneous notes in a timbre (electronic organ) I have little experience with are really hard to tease apart. I've been listening to it on repeat, hoping eventually it will sink in, but it might not.

Contrast this with Steve Reich's [Four Organs](https://www.youtube.com/watch?v=w0yTZmMgI5I). I think that if I sat down at an organ and tried a few different configurations, I could figure out the opening chord exactly (or I could look at the score). But more importantly, each new note, each new _idea_ is introduced one at a time, and I can process it: THere's an F# to an E, there's a G# to an A. 

Life is not like this. Input comes in too fast and I'm overwhelmed, another day too slow and I'm  bored. Reich's music cuts right down the middle. It is soothing, a finely crafted engine: it enjoins me to keep moving.

If I'm ever asked what I like about minimalism, this is what I'd say.

For what it's worth, the introduction to Nausicaä provides different pleasures. It's a rainy Sunday in the suburbs in a pandemic; I may listen to it 100 times today and still fail to parse the mystery, overmatched, beyond ken.
