---
title: All the words in _Lord of the Rings_ that I did not know
author: Seth Ariel Green
date: "2020-07-22"
tags:
- fantasy-literature
- lord-of-the-rings
slug: all-the-words-in-lord-of-the-rings-that-i-did-not-know
---

Sixty-four in all! I had a sense of what some of these meant but included them if I wasn't pretty sure,and a lot of the usages were archaic.

The joy of putting together a list like this was both learning a bunch of fun words and also engaging with the people who have tread before me in the task of understanding LOTR's minutiae, e.g., the folks who wrote the [Tolkien Glossary](http://www.tolkienenglishglossary.com/Lord_of__The_Rings/Lord_of_the_Rings_T_-_Z/lord_of_the_rings_t_-_z.html) and [Tolkien and the OED](https://www.oed.com/applib/newsitem/30/tolkien-and-the-oed).

1. **adamant**: _Noun_: very hard native crystalline carbon valued as a gem; _Adjective_: impervious to pleas, persuasion, requests, reason.
2. **affray**: _Noun_: noisy quarrel; a noisy fight.
3. **biers**: _Noun_: a coffin along with its stand; a stand to support a corpse or a coffin prior to burial.
4. **boles**: _Noun_: The stem or trunk of a tree; something similar to this in shape, as a pillar.
5. **boss ** (as in "shield boss"): _Noun_: a round, convex or conical piece of material at the centre of a shield.
6. **buckler**: _Noun_: armor carried on the arm to intercept blows.
7. **charnel**: _Noun_: a vault or building where corpses or bones are deposited; _Adjective_: gruesomely indicative of death or the dead.
8. **commons **: _Noun_: Food provided at a common table; as in colleges; hence food or provisions in general. Short commons -small meals. Of things: not coming up to some standard of measure or amount; inadequate in quantity; insufficient rations, scant fare.
9. **coomb**: _Noun_: Comb. A narrow valley or deep hollow, esp. one inclosed on all sides but one.
10. **corslet**: _Noun_: a piece of body armor for the trunk; usually consists of a breastplate and back piece.
11. **crocks**: _Noun_: An earthen pot, jar or other vessel; earthenware.
12. **culvert**: _Noun_: a transverse and totally enclosed drain under a road or railway.
13. **damask**: _Noun_: a table linen made from linen with a damask pattern; a fabric of linen or cotton or silk or wool with a reversible pattern woven into it; _Adjective_: having a woven pattern.
14. **defile **: _Noun_: a narrow pass (especially one between mountains; _Verb_: place under suspicion or cast doubt upon; make dirty or spotty, as by exposure to air; also used metaphorically; spot, stain, or pollute.
15. **dell**: _Noun_: A deep, natural hollow in land, often with wooded slopes; a small valley; a vale.
16. **dingle**: _Noun_:a tree-shadowed dell, a small wooded hollow.
17. **dolven**: _Verb_ (Adjective in context): Delve. Make or obtain by digging.)
18. **dwimmer**: _Adjective_: (nonce word) Knowledgeable, crafty, or skilled in the art of magic.
19. **eaves**: _Noun_: the overhang at the lower edge of a roof.
20. **embrasure**: _Noun_: an opening in a wall or ship or armored vehicle.
21. **eyot**: _Noun_: An islet; an ait (a small island in a river).
22. **eyrie**: _Noun_: the lofty nest of a bird of prey, such as a hawk or eagle; any habitation at a high altitude.
23. **fastness**: _Noun_: a strongly fortified defensive structure.
24. **fen**: _Noun_: low-lying wet land with grassy vegetation; usually is a transition zone between land and water.
25. **flet**: _Noun_: From Middle English flet (“floor of a house; house”).
26. **fosse**: _Noun_: ditch dug as a fortification and usually filled with water.
27. **furlong**: _Noun_: a unit of length equal to 0 yards.
28. **gangrel**: _Adjective_: A vagabond or vagrant; also, a lank, loosely built person.
29. **haft**: _Noun_: the handle of a weapon or tool.
30. **hayward**: _Noun_: An officer having the charge of hedges and fences, esp., to keep cattle from straying through; also a herdsman of cattle feeding on a common (common land where anyone could graze their cattle, sheep, etc.).
31. **hauberk**: _Noun_: a long (usually sleeveless.
32. **hillock**: _Noun_: a small natural hill.
33. **hummock**: _Noun_: A knoll or hillock (a small hill or mound).
34. **hythe**: _ Noun_: Hithe. A port or haven; esp., a landing place on a river.
35. **islet**: _Noun_: a small island.
36. **kerb**: _Noun_: an edge between a sidewalk and a roadway consisting of a line of curbstones (usually forming part of a gutter.
37. **laved**: _Verb_: wash or flow against; cleanse (one's body, wash ones face and hands).
38. **lee**: _Noun_: Shelter; esp., the side or part that is sheltered or turned away from the wind.
39. **louver**: _Noun_: A turret or lantern on the roof of a medieval building, to supply ventilation or light; one of a set of parallel slats in a door or window to admit air and reject rain.
40. **mere **: _Noun_: a small pond of standing water; 
41. **moot** (as in "Shire moot"): _Noun_: an Anglo-Saxon legal institution, used to maintain law and order at a local level, and perform various administrative functions, including the collection of taxes for the central government.
42. **muster **: _Noun_: a gathering of military personnel for duty; compulsory military service; _Verb_: gather or bring together; call to duty, military service, jury duty, etc..
43. **nasturtiums**: _Noun_: any tropical American plant of the genus Tropaeolum having pungent juice and long-spurred yellow to red flowers; aquatic herbs; flowers and seeds and leaves all used as flavorings.
44. **ostler**: _Noun_: someone employed in a stable to take care of the horses; An innkeeper; also; one who cares for horses at an inn; any person who takes care of horses; a groom.
45. **pikestaff**: _Noun_: the staff of a pike.
46. **postern**: _Noun_: a small gate in the rear of a fort or castle.
47. **provender**: _Noun_: food for domestic livestock; a stock or supply of foods.
48. **ramifying**: _Verb_: have or develop complicating consequences; grow and send out branches or branch-like structures; divide into two or more branches so as to form a fork.
49. **recreant**: _Noun_: an abject coward; a disloyal person who betrays or deserts his cause or religion or political party or friend etc.; _Adjective_: having deserted a cause or principle; lacking even the rudiments of courage; abjectly fearful.
50. **rede **: _Noun_: advice or counsel given by one person to another; To counsel or advise; also to explain or interpret; also to relate or tell; a plan, design, or scheme.
51. **sable **: _Noun_:  a very dark black; an artists brush made of sable hairs, the expensive dark brown fur of the marten;; a scarf (or trimming; marten of northern Asian forests having luxuriant dark brown fur).
52. **sortie**: _Noun_: a military action in which besieged troops burst forth from their position; (military; as in a military operation.
53. **sties**: _Noun_: an infection of the sebaceous gland of the eyelid; a pen for swine.
54. **sward**: _Noun_: surface layer of ground containing a mat of grass and grass roots.
55. **swart**: _Adjective_: naturally having skin of a dark color.
56. **troth**: _Noun_: a mutual promise to marry; a solemn pledge of fidelity.
57. **truncheon**: _Noun_: a short stout club used primarily by policemen.
58. **trussed**: _Verb_: tie the wings and legs of a bird before cooking it; secure with or as if with ropes; support structurally; _Adjective_: bound or secured closely; support (a roof, bridge, or other structure) with a truss or trusses.
59. **turves**: _Noun_: surface layer of ground containing a mat of grass and grass roots; the territory claimed by a juvenile gang as its own; range of jurisdiction or influence.
60. **tussock**: _Noun_: a bunch of hair or feathers or growing grass.
61. **wanly **: _Adverb_: in a weak or pale or languid manner.
62. **warren**: _Noun_: A habitation having passages like burrows. A building or collection or buildings containing many tenants in limited quarters. The word is associated with rabbits, rabbit holes, etc.
63. **whin**: _Noun_: Basaltic rock; any of various other hard rocks; also, a mass or piece of such rock.
64. **yale**: _Noun_: Fertile upland).



```{r, include=FALSE, eval=FALSE}
library(reticulate)
use_miniconda(condaenv = 'r-reticulate', require = T)

# check that everything works
py_config()
py_available()
reticulate:::miniconda_meta_path() # what is up with this three dots thing?
conda_version()
conda_binary()
all.equal(system('which python'), conda_python()) 
```


```{bash, eval=FALSE, include=FALSE}
pip install PyDictionary
```

 
```{python, eval=FALSE, include=FALSE}
from PyDictionary import PyDictionary

# import aned sort words
# words = sorted(open('static/post/2020-07-14-all-the-words-in-lord-of-the-rings-that-i-did-not-know_files/lotr-words')) # this doesn't exist anymore (did I delete it or )

# strip newline characters
words = [w.replace('\n', '') for w in words]

# put whole thing into PyDictionary (this was tricky - I was trying to loop over
# the items a bunch of different ways but PyDictionary can take in a list input)
lotr_dict = PyDictionary(words).getMeanings()
# append a few words that PyDictionary didn't know
lotr_dict.update({"coomb":""})
lotr_dict.update({"dolven":""})
lotr_dict.update({"dwimmer":""})
lotr_dict.update({"eyot":""})
lotr_dict.update({"flet":""})
lotr_dict.update({"gangrel":""})
lotr_dict.update({"hayward":""})
lotr_dict.update({"hythe":""})
lotr_dict.update({"vestering":""})
lotr_dict.update({"yale":""})
lotr_dict.update({"gangrel":""})

i = 1
for item in lotr_dict.items():
  print(i, ". ", item, sep="")
  i +=1

# start by printing something nice to the console
i = 1
for word in zipped_dict:
  print(i, ": ", word, "\n")
  i +=1

```



```{python, cutouts, include=FALSE, eval=FALSE}
words.__class__
print(list(words))
print(words) 
for word in list(words):
  print(word)

my_list = ['this\n', 'is\n', 'a\n', 'list\n', 'of\n', 'words\n']
new_list = map(str.strip, my_list)
for item in new_list:
  print(item)

for word in words:
  word = words.strip()
  lotr_dict

with open('static/post/2020-07-14-all-the-words-in-lord-of-the-rings-that-i-did-not-know_files/lotr-words-defined.txt','w+') as f:
  i=1
  for word in test_words:
#    word = test_words.strip()
    f.writelines(str(i))
    f.writelines(". ")
    f.writelines(word)
    f.writelines(": ")
    f.writelines(str(dictionary.meaning(word)))
    f.writelines("\n")
    i +=1

# f = open('static/post/2020-07-14-all-the-words-in-lord-of-the-rings-that-i-did-not-know_files/lotr-words-sorted', "a")
print(words)
# import os
# os.chdir('/Users/setgree/Dropbox/GitHub/setharielgreen/')

  #if word.strip("\n"):
    print(word, ":", "definition", "\n")