---
title: I've been zeitgeisty lately
author: Seth Green
date: '2021-09-14'
slug: i-ve-been-zeitgeisty-lately
categories: []
tags: []
---

I:

* was a [zoomtown-er](https://www.fastcompany.com/90564796/zoom-towns-are-exploding-in-the-west) in Park City in  October 2020;

* [left my job to pursue personal projects](https://www.nytimes.com/2021/04/21/technology/welcome-to-the-yolo-economy.html) in April 2021

* [got an unsanctioned booster shot](https://www.nytimes.com/2021/09/14/us/politics/coronavirus-booster-shots.html) a few days ago.^[This one I will explain. I got the J&J shot in April 2021. When I got back to NY in August from traveling, I was worried about breakout cases. The fact that I got one dose in the first place rather than two seems to have been an artifact of clinical trial decisions rather than something cognizably scientific; we often see that boosters povide immunogenic response, like, in general; and, contra one of the dumbest things [I've read in a newspaper](https://www.nytimes.com/live/2021/02/03/world/covid-19-coronavirus#astrazeneca-coronavirus-vaccine), I think we can indeed make generalizations between vaccines. So I got a second; I felt no ethical compunction about lying when they asked me if I had been vaccinated already I also didn't think it was morally relevant that other people who are more deserving of a shot haven't gotten theirs yet; I don't think my declining a shot would lead to some more deserving person getting hers faster.]

I wonder if the trend of being trendy will continue? I also am prompted to think about much the ideas that feel original or appealingly counternormative to me are just generally 'in the air.'
