---
title: '''I''m an ethical vegan, and not the fun kind'''
author: Seth Green
date: '2020-12-20'
slug: i-m-an-ethical-vegan-and-not-the-fun-kind
categories: []
tags: []
---


On an episode of _Indian Matchmaking_, [our hero Nadia](https://www.oprahmag.com/entertainment/a33456690/where-is-nadia-now-indian-matchmaking/) meets a potential suitor named Vinay at a restaurant and learns that he keeps to a vegan diet. "It was honestly just curiosity," he says. "Are you ok if I get..." Nadia trails off. "Oh yeah yeah, of course!" he says. "Like, I grew up non-veg, Like uh, thirty-five years of my life is non-veg," and they laugh about it. It was an awkward moment, but they've skated past it, because he's the cool kind of vegan, not one of those preachy PETA people, heaven forbid. We know the type: he's doing it for health reasons, but it's totally a personal thing, and no worries, it's completely cool if you get chicken, he's heard it's really good here! 

I myself am not the cool kind of vegan, and I think people sense this. When the subject comes up, a fair proportion of my interlocutors immediately steer the conversation towards a place where the next, prescribed step in the dance is for me to affirm my non-judgementalness, e.g. asking me  "is it a health thing?" When I say, no, it's because of the factory stuff farming that we all know is wrong but try not to think about, I am usually met with sympathy, and perhaps a declaration of their own efforts in that direction: "I try to only eat meat at restaurants," or "I get all my turkey from a local butcher," etc. And that's typically the end of that part of the conversation. 

Contrast this with my bringing up that a close friend raised her dog on a vegan diet (technically, [ostrovegan](https://www.berkeleywellness.com/healthy-eating/food/article/what-ostrovegan), which is also the diet I follow). This news elicits something much stronger than sympathy: disgust, and potentially anger, especially among people who have dogs. "There's no way that's good for the dog's health," they might say. Never mind that my friend consulted with an expert in canine nutrition for dogs about how best to do it,^[In her experience, $100 can buy you an hour on the phone with a world-class DVM on a subject of your choosing, and they'll email you follow-up information about the topic on their own time. The equivalent rate for a comparably prestegious MD -- would it be 4 figures, or 5? I honestly don't know.] or that being slaughtered for dog food is probably not very good for a cow's health, and that that might matter to us. No, the dog's health is paramount, and did you know that meat for dogs is just a byproduct of meat produced for humans' consumption, so how could you hurt your pup like that? 

The difference between these scenarios, I think, is that the second definitively resolves any any ambiguity about what kind of vegan I am: not the fun kind. It is certainly not for personal reasons if I think that the imperative to avoid causing great harm to sentient creatures, unless there's a really good reason for doing so  (and "mmm, yum!" doesn't cut it), also extends to any non-persons under our care.^[I know that some people think that dogs are people, and I don't definitively know that they are not. For now, I'll say that I don't think that dogs are people, and neither are baby humans, but both are still precious and worth protecting.] I have instead revealed myself to be the bad, low-status kind of vegan, the preachy kind, the one it's safe to [make memes about](https://www.buzzfeed.com/awesomer/spot-the-vegan) and sneer at. 

I think Andrea Dworkin would really get this, and I wish she was alive right now; I would like to write her a letter. ["I'm a radical feminist," she once said. "And not the fun kind."](https://www.nytimes.com/2019/02/22/opinion/sunday/trump-feminism-andrea-dworkin.html) I fucking love that. And I'm not the fun kind of vegan, I want to tell her. It took actual courage for her to say that, and to live it. So thank you, Andrea Dworkin. Your steadfastness is a light to me. [I wish that we could talk about it](https://www.youtube.com/watch?v=eISo-iFGGDg).




