---
title: Would that every great artist had a disco period
author: Seth Green
date: '2024-07-15'
slug: []
categories: []
tags: []
---

I saw RJD2 spin a few weeks ago and I was very pleased to hear him play The Who's [Eminence Front](https://open.spotify.com/track/0LN5gIsS5tQSmRzQrHSaTR?si=a3a7a5cc79804a21), a great disco-influenced track whose keyboards evoke (for me) Steve Reich's [Four Organs](https://open.spotify.com/track/1c2F2h6Af9skg91Wp5xl1Q?si=103c13efea914bd8) or the [opening theme to Nausicaä](https://open.spotify.com/track/0QW4RCyj2Tc2N0hD1FjkcS?si=69983ff2697e404a). Among great rock artists pivoting to disco, I'd put this track second in my personal pantheon, behind only Paul McCarthey's [Temporary Secretary](https://open.spotify.com/track/4zcoGX2OQMMf4gs6KO9jzX?si=1a91fc17ab8c4272), which, as far as I know, sounds like nothing else ever recorded. 

Also high on my list are [I Miss You](https://open.spotify.com/track/3hJLKtTpgct9Y9wKww0BiR?si=78c9d3f29c684661) and [50 Ways to Leave your Lover](https://open.spotify.com/track/6Qb7gtV6Q4MnUjSbkFcopl?si=a54a7cf7a750491d). Hearing these songs "[is kind of like finding out Brian Wilson had a desert period](https://www.nytimes.com/2018/05/24/arts/okeeffes-hawaii-paintings.html?auth=login-google1tap&login=google1tap)." It's such a pleasure hearing geniuses venture into adjacent fields. Another one that comes to mind is the ending to Radiohead's [Electioneering](https://open.spotify.com/track/0gTRROuntlrPQ64W3J2Etv?si=8c996b49429d48f5), where we learn that they could have been an outstanding heavy metal act.

At the [Noguchi Museum](https://www.noguchi.org/), the tour guide may tell you that when Noguchi felt that he had mastered something, he ventured into other forms. I admire that, though I probably won't emulate it. I'm so far from mastery of anything that I can't really imagine getting bored and moving further afield. 

Every day we must hone the craft. But if you're Paul McCartney, you might as well take the risk, for which I'm gateful. 

