---
title: An adjective I think about a lot
author: Seth Green
date: '2020-10-28'
slug: an-adjective-i-think-about-a-lot
categories: []
tags: []
---

In [An Electronic Soundtrack for Spiritual Awakening](https://www.newyorker.com/magazine/2018/04/30/an-electronic-soundtrack-for-spiritual-awakening), Kelefa Sanneh calls Jon Hopkins "one of the most celebrated electronic musicians of his generation."  Now, I like Hopkins's music a lot -- [Collider](https://www.youtube.com/watch?v=8XtqUOegCv8), [Light Through the Veins](https://www.youtube.com/watch?v=1H3pA4X-mhA), [Open Eye Signal](https://www.youtube.com/watch?v=Q04ILDXe3QE), and [Emerald Rush](https://www.youtube.com/watch?v=4sk0uDbM5lc) are all a lot of fun  --  but "one of the most celebrated"? I think not, at least, not the way Metro Boomin's tracks with Future are literally present at celebrations all around America, because he makes, get this, _popular music_. 

Ditto for Lex Luger, DJ Mustard, Madlib, A-Trak, and Hit-Boy, artists whose music is probably being greeted with a  clinking of beer bottles or salute of blunts this very moment, whenever you are reading this. The _New Yorker_ would not have called Hopkins "well-liked by magazine writers and their friends in Brooklyn," but I think that's what is meant by 'celebrated' here.

The other elision in this sentence is that Electronic Music is being held distinct from its sister genre, Electronic Dance Music, with its big, obvious sounds and people (Cf. Steve Aoki and Diplo), and also walled off from the less-well-contoured genre of "hip hop whose sounds are electronically produced rather than acoustic samples." Because if you consider all that electronic music, I think you'd conclude that Metro Boomin is the most celebrated electronic artist in America.^[Here is [Donald Glover celebrating MB's track with Migos, 'Bad and Boujee'](https://www.youtube.com/watch?v=QxJ3nVjRZHE), at the Golden Globes.] And [Leland Tyler Wayne](https://en.wikipedia.org/wiki/Metro_Boomin)  wasn't putting out prestige albums under his own name, then or now; he was making hits for rappers, creating space for others to shine.

Here are some songs of Metro Boomin's that I like:

* [Solange - Stay Flo (Official Audio)](https://www.youtube.com/watch?v=_W14wK4QGh4)
* [Future - My Collection instrumental](https://www.youtube.com/watch?v=bCRWyDBSBBk)
* [Bad & Boujee - Migos (instrumental](https://www.youtube.com/watch?v=LvockvKVxpc)
