---
title: Venom, an emotionally self-aware ubermensch
author: Seth Green
date: '2024-01-23'
slug: venom-an-emotionally-self-aware-ubermensch
categories: []
tags: []
---

I have a soft spot for movies that get away from their creators. I don't think that Tony Scott, for instance, intended _Top Gun_ to be a quintessentially gay movie. I think instead that he longed for a richer set of homosocial relationships, where men can like, love, hate, compete, fight, make up, and simply be close to one another all the time. Ancient people would not have questioned this, nor its [obvious erotic overtones](https://www.esquire.com/entertainment/movies/a39918358/top-gun-volleyball-scene-gay/); the [collective unconscious ](https://www.thecollector.com/carl-jung-controversial-idea-what-is-collective-unconscious/) emerges.

Likewise with _Venom: Let There Be Carnage_, which I watched on a plane recently. One review called it a '[buddy movie](https://www.hollywoodreporter.com/movies/movie-reviews/venom-let-there-be-carnage-review-1235022883/),' but I think this misses what's weird and rich about the text.

First, the characters essentially inhabit the same body, with one or the other in control of the levers at different points. When Eddie is at the reins, he hears Venom's voice, and vice versa when Venom is in control.  Do they experience each other's pleasures? I think the answer is that Venom experiences Eddie's pleasures, judging by how enthusiastically he encourages Eddie to get back together with Anne; but Eddie never expresses any enthusiasm for Venom's pleasure, which, mainly, is eating brains. Eddie seems disgusted and horrified by the experience and sets strict rules on what brains Venom is allowed to eat (mainly to avoid attracting legal issues). 

Here's a theory: Eddie _does_ experience Venom's pleasure, but doesn't allow himself to feel it. In Freudian terms, Eddie is the superego and Venom is the id. I think this model fits a lot better than "buddy movie." 

Where things get weird, though, is that Venom is generally much more emotionally well-adjusted than Eddie is. Venom is in touch with his feelings. Venom does not lie to Anne about what he wants and what he's feeling, like Eddie does, and Venom is clear and consistent about when he's hurting or when he's sorry for his behavior. After Venom and Edie split, Venom's reaction is child*like* but not child*ish*; he seeks validation from a crowd of partygoers and, in turn, spreads the good vibes back to them. Meanwhile we see Eddie miming adulthood: tidying his apartment, [vacuuming](https://www.nytimes.com/2023/11/28/style/dyson-cordless-vacuum-status-symbol.html), cleaning up Venom's mess. But Eddie, fundamentally, is a lazy, vindictive man who, without Venom's superhuman memory and attention for details, would be nowhere professionally. Yet Eddie is incapable of expressing gratitude. Eddie is inarticulate, pointless; he ends the movie in a hotel bed watching a soap opera, a man who has failed to launch.

This is very strange behavior for a superego and an id. Rather, I think the best model for their relationship is that Venom has transcended traditional morality, with all its hangups; he has gone '[beyond good and evil](https://en.wikipedia.org/wiki/Beyond_Good_and_Evil).' The movie can't endorse this position, or follow it to its weird, logical endpoint (Venom keeps trying to live an independent life, or Eddie agrees that eating brains is fun and they become [The Lethal Protector](https://en.wikipedia.org/wiki/Venom:_Lethal_Protector) in earnest). But Venom is clearly the protagonist of the film, clearly the character with a consistent moral vision and lack of shame, clearly the only one you'd watch a movie about. A better movie would have just been about that, rather than a conflict with an alien, a woman who has suffered unjust imprisonment for her entire life, and a serial killer (none of whose motives or behaviors make any sense).
