---
title: I want my words to tell the story
author: Seth Green
date: '2021-06-14'
slug: i-want-my-words-to-tell-the-story
categories: []
tags: []
---

In late summer 2010, I was on a bus one evening in Philadelphia, returning to Swarthmore. A man came on who had the words 'Fuck em all' tattooed across his chest. I looked at that man, probably more than was polite or advisable, and thought about it. Every single day, that man woke up and had that attitude branded on his skin. By contrast, I could take a shower and put on a suit one morning and fit in in a consulting firm; or a tie dye shirt and a hemp necklace and look natural at a music festival. That was precious to me, I realized. So I decided to never get a tattoo. I cherished being protean. My words and my outfits and ornaments can tell the story, whatever story I like. 

Today I am more aware of the costs of trying to be many things. I have tried, and failed, to fit into enough molds that didn't work to know that there is an essential Seth who can't tell any story, at least not persuasively. People find me out, they identify the impostor. And the psychic costs are both acute and cumulative: [A heart, that's, full up like a landfill](https://www.youtube.com/watch?v=u5CVsCnxyXg).

I am not saying that I plan to get a tattoo. But I no longer wish like I once did to be fluid, lest I pour myself into a groove that someone else forged, in time emptied out, or stuck in a bend. 

This is just to say that I am hiking the Appalachian Trail now and thinking about what kind of life I want to live. A lot of things about prior directions and plans weren't working. I'm not sure what comes next. But in the meantime I am contemplating it. 

I am posting photos periodically to [Instagram](https://www.instagram.com/setgree/). 
