---
title: Social Media Manager as a distinct professional class
author: Seth Green
date: '2023-10-15'
slug: social-media-manager-as-a-distinct-professional-class
categories: []
tags: []
---



<p>I have now worked in marketing and marketing-adjacent jobs at <a href="https://codeocean.com/">two</a> <a href="https://glodollar.org/">startups</a>, producing <a href="https://www.glodollar.org/articles/glo-zero-poverty-and-the-sdgs">blog</a> <a href="https://medium.com/codeocean/two-welcome-innovations-in-liu-and-salganik-2019-successes-and-struggles-with-computational-b4ef1a4311f2">posts</a>, <a href="https://twitter.com/glodollar/status/1580906280599724032">social</a> <a href="https://twitter.com/CodeOceanHQ/status/989193597294665729">media</a>, and <a href="https://forum.effectivealtruism.org/posts/EAiwxZN4Jiyup8d9G/glo-dollar-an-ethical-stablecoin-model-potential-impact-and">external</a> <a href="https://www.cambridge.org/core/blog/2018/12/21/public-and-private-benefits-to-practicing-open-science/">content</a> under the tutelage of two directors of marketing, a head of growth, and a chief marketing officer. I’ve learned that marketing is a quasi-discipline with <a href="https://monzo.com/tone-of-voice/">sacred texts</a>, <a href="https://seths.blog/">gurus</a>, widely understood conceptual divisions (I mostly did <a href="https://mailchimp.com/marketing-glossary/content-marketing/">content marketing</a>, as opposed to <a href="https://blog.hubspot.com/marketing/product-marketing">product marketing</a> or <a href="https://www.optimizely.com/optimization-glossary/growth-hacking/">growth hacking</a>), and dogmas about what tactics are appropriate to which situations (e.g. ‘<a href="https://www.semrush.com/blog/outbound-links/">outbound links</a>’ are <a href="https://prdaily.com/linkedin-algorithm-update-company-page/">penalized on LinkedIn</a> but, until recently, not on Twitter).</p>
<p>Apparently there is some sort of widely parallelized curriculum that’s been distributed and reproduced through professional marketing networks, such that marketing executives can all talk to each other about SEO tactics and the proper structure of Twitter threads using language and concepts that the rest of us do not have easy access to. If we happen to overhear this conversation or be party to it, we might intuit that some of the underlying theories of consumer behavior are not well-grounded, or that tactics which worked in one situation might produce no effect elsewhere. But raising these doubts, in my experience, pits an amateur against an expert who specializes in selling things. In general, they’re going to have the upper hand. Something needs to go really wrong to call the underlying paradigm into question.</p>
<p>Recently, two things did.</p>
<p>The first was the running apparel company Tracksmith using elitist, anti-jogger language to promote a <a href="https://runnersworld.com/news/a45486207/tracksmith-boston-marathon-qualifier-singlet-controversy/">singlet for Boston qualifiers only</a>, which they then deleted and <a href="https://www.instagram.com/p/Cx_rR3_Lj67/0">apologized for</a>.</p>
<p>The second was some pro-Palestine Twitter posts from progressive organizations like <a href="https://www.hindustantimes.com/world-news/black-lives-matter-chicago-says-they-aren-t-proud-of-now-deleted-post-supporting-hamas-attack-on-israel-101697086107172.html">BLM Chicago</a> and various <a href="https://www.timesofisrael.com/us-democrats-lash-socialist-organization-for-backing-rally-supporting-hamas-attack/">DSA groups</a>. This has, apparently, <a href="https://www.politico.com/news/2023/10/11/dsa-rally-aoc-israel-00121060">“caused the beginnings of a major rift within the DSA.”</a></p>
<p>Here’s an alternative: blame the social media managers. As a class, they’ve capitalized on widespread confusion about what social media is, and how to use it, to carve out powerful, public-facing fiefdoms. The bosses leave them to their own (literal) devices, because they tend to be older and less internet-savvy; but the whole edifice, I think, is a house of cards.</p>
<p>Let’s put amateurs at the helm again.</p>
