---
title: Social Media Manager as a distinct professional class
author: Seth Green
date: '2023-10-15'
slug: social-media-manager-as-a-distinct-professional-class
categories: []
tags: []
---

I have now worked in marketing and marketing-adjacent jobs at [two](https://codeocean.com/) [startups](https://glodollar.org/), producing [blog](https://www.glodollar.org/articles/glo-zero-poverty-and-the-sdgs) [posts](https://medium.com/codeocean/two-welcome-innovations-in-liu-and-salganik-2019-successes-and-struggles-with-computational-b4ef1a4311f2), [social](https://twitter.com/glodollar/status/1580906280599724032) [media](https://twitter.com/CodeOceanHQ/status/989193597294665729), and [external](https://forum.effectivealtruism.org/posts/EAiwxZN4Jiyup8d9G/glo-dollar-an-ethical-stablecoin-model-potential-impact-and) [content](https://www.cambridge.org/core/blog/2018/12/21/public-and-private-benefits-to-practicing-open-science/) under the tutelage of two directors of marketing, a head of growth, and a chief marketing officer. I've learned that marketing is a quasi-discipline with [sacred texts](https://monzo.com/tone-of-voice/), [gurus](https://seths.blog/), widely understood conceptual divisions (I mostly did [content marketing](https://mailchimp.com/marketing-glossary/content-marketing/), as opposed to [product marketing](https://blog.hubspot.com/marketing/product-marketing) or [growth hacking](https://www.optimizely.com/optimization-glossary/growth-hacking/)), and dogmas about what tactics are appropriate to which situations (e.g. '[outbound links](https://www.semrush.com/blog/outbound-links/)' are [penalized on LinkedIn](https://prdaily.com/linkedin-algorithm-update-company-page/) but, until recently, not on Twitter). 

Apparently there is some sort of widely parallelized curriculum that's been distributed and reproduced through professional marketing networks, such that marketing executives can all talk to each other about SEO tactics and the proper structure of Twitter threads using language and concepts that the rest of us do not have easy access to. If we happen to overhear this conversation or be party to it, we might intuit that some of the underlying theories of consumer behavior are not well-grounded, or that tactics that worked in situation A might fail in situation B. But raising these doubts, in my experience, pits an amateur against a subject matter expert who specializes in selling things. In general, they're going to have the upper hand. Something needs to go really wrong to call the underlying paradigm into question.

I observed two recent social media snafus that brought this to mind. 

The first was the running apparel company Tracksmith using anti-jogger language to promote a [singlet for Boston qualifiers only](https://runnersworld.com/news/a45486207/tracksmith-boston-marathon-qualifier-singlet-controversy/), which they then deleted and [apologized for](https://www.instagram.com/p/Cx_rR3_Lj67/0).

The second was some pro-Palestine Twitter posts from progressive organizations like [BLM Chicago](https://www.hindustantimes.com/world-news/black-lives-matter-chicago-says-they-aren-t-proud-of-now-deleted-post-supporting-hamas-attack-on-israel-101697086107172.html) and various [DSA groups](https://www.timesofisrael.com/us-democrats-lash-socialist-organization-for-backing-rally-supporting-hamas-attack/). This has, apparently, ["caused the beginnings of a major rift within the DSA."](https://www.politico.com/news/2023/10/11/dsa-rally-aoc-israel-00121060)

Here's an alternative: blame the social media managers. As a class, they've taken advantage of widespread confusion about what social media is, and how to use it, to carve out powerful, public-facing fiefdoms. CEOs and nonprofit directors leave them to their own devices; but the whole edifice, I think, is a house of cards. 

Let's put amateurs at the helm again. 
 
