---
title: Contagion and A.I., a parable and a fairy tale
author: Seth Green
date: '2022-03-11'
slug: contagion-and-a-i-overt-and-oblique-animal-rights-parables
categories: []
tags: []
---

[Contagion](https://www.imdb.com/title/tt1598778/) got a lot of attention these past few years for being [eerily predictive](https://variety.com/2020/film/columns/contagion-the-movie-that-predicted-our-pandemic-1234590420/) and apparently inspiring some aspects of the [UK's  pandemic response](https://www.theguardian.com/film/filmblog/2021/feb/04/contagion-film-matt-hancock-covid-vaccine-policy-hollywood). I watched it last night, and it is indeed unnerving. I like the shots that lingered on high-touch surfaces; Sodenbergh knows that you're thinking of all the times you've been in all-too-close proximity with a sick person, and all the residue they leave behind.

But the movie really came together for me in its [last 80 seconds](https://www.youtube.com/watch?v=BwJvtbmlriA), which show a bulldozer destroying a bat's habitat, who then settles into a pigpen and infects a pig, who is then taken away, killed off-screen, and prepared for consumption by a chef who poses for a photo with Gwyneth Paltrow's character as the words 'Day 1' appear on-screen. (We've already learned that she's the [index case](https://en.wikipedia.org/wiki/Index_case).) This is a very plausible genesis story for a global pandemic, but why include it at all? Why not end with Matt Damon's character and his daughter celebrating a return to normalcy? 

I think the last scene serves to turn the movie into a parable, and I read it as explicitly about animal rights. First we destroy their habitat, then we slaughter them, and it's not so much that they take *vengeance* on us as our carelessness with their lives and welfare is likely to be balanced out against us. You can call this 'environmental justice,' but notice that most of this scene, though it's prompted by environmental destruction, focuses on the bat, the pig, and then the chef. _That's_ the cycle Soderbergh wants us to attend to, and the pig's sweet face, her curious manner. We should have left her alone, the movie says.^[I am surprised to see this aspect of the film not explicated more in reviews and commentary.]

Contrast this with [A.I. Artificial Intelligence](https://en.wikipedia.org/wiki/A.I._Artificial_Intelligence), which I watched last fall and found quite moving. Tim Kreider [calls the Star Wars prequels](https://www.nytimes.com/2019/12/20/opinion/star-wars-movie.html) "the most depressing blockbusters of all time — kids’ adventure films whose boy hero ends up a baby killer." I understand his point, but I think A.I. takes the bleak cake.^[In the non-blockbuster category, we also have [_The Road_](https://www.imdb.com/title/tt0898367/) and [_The Florida Project_](https://www.imdb.com/title/tt5649144/?ref_=nv_sr_srsg_0), the latter of which ruined my weekend one time.] It features

* an underwater, uninhabited Manhattan in the near future;
* huumans who are  unbearably cruel to the undeniably sentient and intelligent non-humans that they create;
* an entirely extinct human race by the film's end;
* a little boy whose truest dream is to spend one perfect day with his mother, with no one around to distract them, and then to die. (That's how I read his eyes closing in the final shot, anyway.)

The other thing I would call this film, besides bleak, is profoundly anti-progressive. That's not quite 'conservative,' the way that the Dark Knight Rises's [climactic scene](https://www.youtube.com/watch?v=gCEo7SCvYH4) is about the police bravely taking the streets back from [OWS-style anarchists](http://www.mtv.com/news/1690715/dark-knight-rises-occupy-wall-street/) -- "there's only one police in this town," one of them actually says! -- or 'reactionary' the way [_Dredd_](https://web.archive.org/web/20120906080612/http://whatculture.com/film/alex-garland-interview-dredd-3d-slo-mo-sequel-ideas-more.php) is about a one-man army who righteously slaughters the bad drug dealers. No, I mean anti-progressive in that it denies the truth of the MLK maxim that "the arc of the moral universe is long, but it bends toward justice." In _this_ future, we've vastly expanded the ranks of conscious beings, and we hate them. [We massacre them in a 'flesh fair'](https://www.youtube.com/watch?v=ZMbAmqD_tn0). David, the main character, escapes only when people are revolted by his resemblance to a 'real boy' and rebel. 

If we can't extend our [moral circle](https://www.vox.com/future-perfect/2019/4/4/18285986/robot-animal-nature-expanding-moral-circle-peter-singer) towards intelligent creatures unless they look _exactly like our children_, what hope is there for us to care about [octopuses](https://www.nytimes.com/2018/11/30/science/animal-intelligence-octopus-cephalopods.html), or [chickens](https://www.nytimes.com/2022/02/10/opinion/factory-farming-chicken.html), or [spiders](https://knowablemagazine.org/article/mind/2021/are-spiders-intelligent)? 

I wouldn't call this a parable, because there's no lesson; the vision is that we're awful and then we die. But it is a fairy tale, and not just because David spends the whole movie pursuing the blue fairy, who grants him his ultimate wish. It's also because the surroundings are scary and don't make any sense and everyone is cruel, like a fairy tale.

Are we seeing this from David's perspective? Some scenes, like where Jude Law's character, Joe, is pulled away from David by drones, clearly are. But others, like that in which Joe is framed for murder, are David-independent. So I think we're supposed to conclude that things really are this apocalyptic, that we really do kill each ourselves en masse without ever achieving enlightenment w.r.t other species.

The only upside is that we _do_ all die, and, presumably, leave everyone else in peace; the moral of the fairy tale is that humans are bankrupt and the world is better off without us.

So yes, I'd say it's probably the bleakest film I've ever seen,^[At least with the Star Wars prequels, we know that there will soon be [A New Hope](https://en.wikipedia.org/wiki/Star_Wars_(film)).] and up there with [Okja](https://en.wikipedia.org/wiki/Okja) and Contagion as a rebuke of our inability to empathize across species.