---
title: A delightful passage in 'A Place of Greater Safety'
author: Seth Green
date: '2024-12-06'
slug: a-delightful-passage-in-a-place-of-greater-safety
categories: []
tags: []
---

Two minor characters are meeting a third for the first time:

> ⁠“Let’s hope we can do as well for you this time,” Pétion said, with gallantry. “And yet you are a Parisian, my friend Brissot tells me?”

> ⁠You’re overdoing the charm, Jérôme, his friend Brissot thought.

> ⁠“Yes, but my husband’s affairs have kept us so long in the provinces that I no longer lay claim to the title. I have so often wished to return—and now here I am, thanks to the affairs of the Municipality of Lyon.”

> ⁠Brissot thought, she talks like a novel.

> ⁠“I’m sure your husband is a most worthy representative,” Pétion said, “yet let us cherish a secret hope that he does not conclude Lyon’s business too quickly. We should hate to lose, so soon, the benefit of your advice—and the radiance of your person.”

> ⁠She glanced up at him and smiled. She was the type he liked—petite, a little plump, hazel eyes, dark auburn ringlets about an oval face—style perhaps a little bit young for her? What would she be, thirty-five? He pondered the possibility of burying his head in her opulent bosom—on some later occasion, of course.

So many things I enjoy about this!

1.  Great word choices. I love "with gallantry" and especially "opulent."

2.  The hilarious final aside: "on some later occasion, of course." As opposed to, like, then and there on the street?!

3.  The puncturing of a certain kind of overwrought novel. [Mantel said](https://www.newyorker.com/magazine/2012/10/15/the-dead-are-real), about her odyssey to get the book published: “I wrote a letter to an agent saying would you look at my book, it’s about the French Revolution, it’s not a historical romance, and the letter came back saying, we do not take historical romances...They literally could not read my letter, because of the expectations surrounding the words ‘French Revolution’—that it was bound to be about ladies with high hair.” In this excerpt, the dialogue is totally romance-y -- the chivalry, the over-the-top flattery -- and then we see what the men are thinking, and, [to quote Lana Kane](https://www.imdb.com/title/tt1622042/characters/nm0878768), "remember: they're *dudes*."

4.  Mantel understands that sex and power are inextricable. Marie Antoinette was [tried for molestation](https://www.newhistorian.com/2015/10/15/marie-antoinette-incest-child-abuse-and-adultery/), Anne Boleyn [for incest](https://www.smithsonianmag.com/history/the-many-myths-of-lady-rochford-the-tudor-noblewoman-who-supposedly-betrayed-george-and-anne-boleyn-180980520/); Danton joked to Robespierre that *Vertu* was [what he practiced on his wife every night](https://www.newyorker.com/magazine/2006/06/05/headless-horseman-france-reign-of-terror), and apparently Robespierre never forgave him for it. (Mantel includes a scene of Danton saying this in *A Place of Greater Safety*.)

5.  Foucault argued, in *History of Sexuality Vol. 1*, that we tell ourselves that our recent ancestors were severely sexually repressed as a way of patting ourselves on the back for being liberated. I don't know about that, but I do know that I am much more engaged in an earthier story. The ultimate lesson, if there is one, of Mantel's book is that guardrails on good conduct -- like trials and standards of evidence -- are discarded only at great peril to society and to our souls. The lesson works for me, and doesn't seem heavy-handed, because the characters are three-dimensional: political, lusty, thoughtful, corruptible, impressionable, stubborn.[^1]

[^1]: Per [the Comet](https://adventuretime.fandom.com/wiki/The_Comet) in *Adventure Time*, the things that make life life: "love, hate, friendship, isolation, jealousy, secrets, violence, video games, ice cream waffles, sadness, madness, power, honor, loyalty, saucy, mothers, fathers, scoundrels."
