---
title: The gazpacho, it scalds me
author: Seth Green
date: '2024-10-03'
slug: the-gazpacho-it-scalds-me
categories: []
tags: []
---

When an _[I Think You Should Leave](https://www.nytimes.com/2023/06/02/magazine/tim-robinson-i-think-you-should-leave.html)_ skit takes me a long time to warm up to, it's usually because the situation for which it's a perfect rejoinder hasn't come my way yet. 

This week, I thought a lot about [poor Howie](https://www.instagram.com/ithinkyoushouldreel/reel/C-3JNiJxhhE/?hl=en) from the charades skit. He wants to enjoy some Gazpacho, but

> **Howie**: This gazpacho soup just burned my lips. 

> **chorus:** The gazpacho? 

>  **Howie:** Yeah, it's been sitting out. It warmed up. 

> **chorus**: It warmed up so much that it burned your lip? 

>  **Howie:** Let me explain something to you. If you're expecting something ice cold, and you bring it up to your lips and it's room temp, it's going to feel like your mouth's on fire. It's gonna feel like your body's on fire.

Recently I was a Howie. I was at a conference of good-hearted folks doing their best to solve important problems, and listening to them present their work, I felt an intense need to shout: _that's not right! You're not doing it right!_ It felt like my body was on fire.

I have more of a filter than Howie. I know that it's inherently ridiculous to be in deep physical discomfort because someone's [causal identification strategy](https://www.aeaweb.org/articles?id=10.1257/jep.15.4.69) is paper thin. But it happens. I'm there experiencing it. The gazpacho is burning my lips. 

(In an interview I can't find, Zach Kanin suggests that the show's most desperate characters, like the ones with too much shit on him who can't breathe, say things like "I don't even want to be around anymore" because they're trying to get out of doing things. That's not how I read them. I read them as genuinely overwhelmed, and only hanging on by a thread in the first place.)
