---
title: a few salient election details
author: Seth Green
date: '2024-11-06'
slug: a-few-salient-election-details
categories: []
tags: []
---

Of the [many](http://johnsalvatier.org/blog/2017/reality-has-a-surprising-amount-of-detail), here are a few that stick out:

1. Harris's got zero votes in 2020 because she has [no natural constituency](https://www.latimes.com/california/story/2019-12-04/skelton-california-senator-kamala-harris-drops-out-presidential-race) and [isn't good](https://www.nytimes.com/2019/11/29/us/politics/kamala-harris-2020.html) at managing a campaign. Why would things have been different this time?

2. Trump is what McCain wanted to be, a true maverick. Getting [Tulsi Gabbard](https://abcnews.go.com/Politics/tulsi-gabbards-transition-democrat-high-profile-role-trumps/story?id=113220531) and [RFK Jr.](https://www.bbc.com/news/articles/c134p2k24nzo) onboard -- dominating [the crank vote](https://www.slowboring.com/p/the-crank-realignment-is-bad-for) without alienating more mainstream Republicans -- is a remarkable accomplishment. 

3. Democrats have bungled governance, [over](https://x.com/AaronGuhreen/status/1854000739653435613) and [over](https://x.com/timurkuran/status/1854023445035503778). It was eye opening to me that Gavin Newsom has apparently always been capable of [making San Francisco a nice place to walk around](https://www.newsweek.com/gavin-newsom-slammed-cleaning-san-francisco-1843412), but only did so when a foreign dignitary was visiting. Who would trust them/us to lead the country? 

4. Trump is a [dangerous](https://x.com/FarnoushAmiri/status/1854111660920738066), [failing](https://www.nytimes.com/2024/10/06/us/politics/trump-speeches-age-cognitive-decline.html) [moron](https://www.politico.com/news/2021/04/23/trump-bleach-one-year-484399). I still agree with [Megan McArdle](https://www.oregonlive.com/opinion/2016/11/trump_has_no_business_being_ne.html) that it's very bad for him to have command of nuclear weapons. I can find a few things to [agree](https://x.com/tracewoodgrains/status/1851588500174303282) [with](https://www.betonit.ai/p/trumps-backdoor-to-open-borders) him about, or to [part](https://www.slowboring.com/p/defund-police-is-a-bad-idea-not-a) strongly from the democrats on, and still put this reason first by a long shot when I'm ranking candidates.

5. Elon is the man of the moment. What he's accomplished in the past 5-10 years, not to mention getting this one right and putting his money where his mouth is about it, beggars belief. It was [insanely stupid](https://x.com/nxthompson/status/1854008314478072129) of Democrats to alienate him.i

6. [We carry on](https://www.youtube.com/watch?v=9Y7HsS4bj-4).