---
title: Marianne Moore and Dan Harmon, inscrutable to the future
author: Seth Green
date: '2022-01-25'
slug: marianne-moore-and-dan-harmon-future-inscrutables
categories: []
tags: []
---

My favorite Marianne Moore poems are generally the ones I understand right away, because they're short, they rhyme, and they're about animals. I like animals. I like the way she describes [rats](https://www.poetryfoundation.org/poetrymagazine/browse?contentId=13107), [chameleons](https://www.poetrynook.com/poem/chameleon-1), and [talismanic seagulls](https://poets.org/poem/talisman). Those poems are lovely and easy to digest. It's a lot more work to figure out what's going on in, e.g., [Diligence is to Magic as Progress Is to Flight](https://blakeleitchpoetry.com/2019/09/09/perspective-diligence-is-to-magic-as-progress-is-to-flight-by-marianne-moore/), or [_To a Prize Bird_](https://www.poetrynook.com/poem/prize-bird), which, I learned when I looked it up, is actually about [George Bernard Shaw](https://moore123.com/2011/11/09/george-bernard-shaw-prize-bird-j-b-kerfoot/). 

The problem is that I don't really have an intuitive sense of what Shaw was like, as a person or as an author. My contact with him is mostly mediated through later interpretations of his work (I liked [She's All That](https://en.wikipedia.org/wiki/She%27s_All_That)!). So I don't really understand how he's a prize bird or not, I just have to take for granted that Moore's comparison makes sense. And there is something distinctly unpleasuarable, at least for me, about taking something on faith.

It so happens that we're in a golden age of allusion-heavy TV comedies. Witness [Charlie and Frank reenacting the jewelery box scene from _Pretty Woman_](https://youtu.be/X2W871gZitU?t=131), or Abed rattling off [nine TV characters](https://tvtropes.org/pmwiki/pmwiki.php/Recap/CommunityS2E19CriticalFilmStudies) that he's like on [_Community_](https://en.wikipedia.org/wiki/It%27s_Always_Sunny_in_Philadelphia),^[In order: Data, Johnny Five, Mork, HAL, KITT, K-9, Woodstock and/or Snoopy, and Spock.] or the Xtacles on [_Frisky Dingo_](https://en.wikipedia.org/wiki/Frisky_Dingo) running through things that [sound like](https://www.youtube.com/watch?v=MjQUIxPXuXQ) [_Flowers for Algernon_](https://en.wikipedia.org/wiki/Flowers_for_Algernon).^[They come up with Harrison Bergeron, Tom Bergeron, and Agamemnon. (In a similar vein, we have a character in _Super Troopers 2_ [deliberately confusing](https://www.youtube.com/watch?v=GfeC2HxziqI) Rhea Perlman and Ron Perlman.)] 

Now, the thing I love about that _Frisky Dingo_ joke is that it manages to be both incredibly dense and also stupid beyond belief; but I also have an intuitive sense of the alluded-to things are about.^[Admittedly these are more superficial references -- I don't need to have read _The Illiad_ to know who the brother of Menelaus is. In fact, the Xctacles' absurdly superficial understanding of the content -- they understand "Flowers for Algernon" only as a series of sounds -- is at the center of the joke.] In the same vein, consider the following dialogue between the cast of _Community_ in the episode [_Aerodynamics of Gender_](https://www.imdb.com/title/tt1640872/quotes/qt3100365):

> | **Annie**: You're really good at it. You're like a machine.
> | **Abed**: Like RoboCop.
> | **Britta**: Exactly like Rowboat Cop. Sharice is a bad rowboat. Sink her.

I laughed a lot at this, but if _RoboCop_ were of some fundamentally different era, I don't think I would have even _heard_ the joke, let alone understood it. And if I had looked it up later, short of watching the film, I would just have to take the show's word for it that that's what _RoboCop_ was like, what it was about. In this sense, _Community_ is rendering itself inscrutable, and therefore, I think, less enjoyable, to future audiences. The context, [that which is scarce](https://marginalrevolution.com/marginalrevolution/2021/12/context-is-that-which-is-scarce.html), will eventually be lost.

[I yearn for context](https://setharielgreen.com/2020/05/25/the-pleasure-of-the-appendices-of-the-lord-of-the-rings/). When I picked up a book about Marianne Moore a few years ago, what I really wanted was the story of how those poems came to be -- the _general_ context of their birth -- but instead what I got was a lot of very _specific_ details about her life.  Contrast that with Louis Auchincloss's _Tales of Yesteryear_, which I enjoyed a lot, and whose stories are pretty light on plot but heavy on the social mores and speech conventions of rich Americans circa 1930-1970. I freely admit that I want to taste the water that past people swam in as much as I want their stories, but Moore's poems don't (or can't, or won't) say such things. They're too sparse. We appreciate their language today today and their density rewards close study. But they're not enjoyable in the same way, I suspect, as they once were to readers for whom George Bernard Shaw and [Benjamin Disraeli](https://blakeleitchpoetry.com/2019/05/14/perspective-to-a-strategist-by-marianne-moore/) were alive and salient.^[Another example: in _Brideshead Revisited_, I found it alien that Julia's faith spelled the end of her relationship with Charles; likewise with Sebastian's wasting away in a monastery in Tunisia.]

So too will the pop culture allusions in _Community_ one day be observed but not felt and so not provide the same pleasure of recognition. Dan Harmon et al. made something of the moment rather than aiming for historical sweep. And there's something really nice about that, about aiming to accomplish something specific in a particular moment. To drive towards living a good life, towards entertaining people around you. So, to Marianne and to Dan, [I say](https://www.poetrynook.com/poem/prize-bird):

> | strut, colossal bird.
> | No barnyard makes you look absurd;
> | your brazen claws are staunch against defeat.

>


