---
title: UX testing for public infrastructure
author: Seth Green
date: '2022-09-19'
slug: ux-testing-for-public-infrastructure
categories: []
tags: []
---


An article in the _Wall Street Journal_ documents [LaGuardia Airport's remarkable turnaround](https://www.wsj.com/articles/laguardia-airport-renovation-lga-terminal-b-11663203700):

> It’s no longer appalling. It’s actually nice. In fact, when a panel of judges recently named the world’s best new airport building, the prestigious honor went to Terminal B. It was a bit like Arby’s winning a James Beard Award.

The design team ran some "clever experiments" see if things worked like intended: 

> One was a live trial in which hundreds of friends and relatives came to a concourse of Terminal B right before it opened in 2018. They were handed tickets for phantom flights and given instructions—grab a coffee before heading to Gate 29, say—as the ORAT experts observed their behavior and studied their feedback. When they realized that certain signage was too subtle and the loudspeakers sounded different in a bustling environment, they added splashes of color and tweaked the volume so that real passengers wouldn’t get lost. 

Ditto with baggage collection:

> They collected 500 pieces of luggage in all shapes and sizes, filled them with free weights and checked the bags more than 300,000 times in total. They even conducted a “crush test” and pushed the system to its limits to make sure it was ready for anything. 

And with bathroom stalls:

> My favorite detail in Terminal B is how the stalls are just wide enough to open the door and roll in a bag without bumping into anything. “We spent an inordinate amount of time on restroom design,” said Mr. Scremin.

In tech, we call this [User Experience (UX) research](https://www.edx.org/course/ux-research), and it's one of those [high-paying software jobs](https://medium.com/@robingomila/from-academia-to-ux-research-25f956ea0d57) that your parents know nothing about. At [Code Ocean](https://codeocean.com/), I played an accessory role in our UX testing, meaning I watched and took notes as my best friend fumbled through a mockup of our platform. When he got something 'wrong', we treated it as a design failure and thought about how we could bring the product into line with his expectations.^[ A recent viral tweet showing someone [struggling to set up their new Apple Watch](https://twitter.com/bnj/status/1569098746167959552) gets at the same intuition.] The reason we do this is that UX is really hard, and because consumer products live or die on usability, we have a big incentive to get it right.

While traveling this summer, I was struck by how much public infrastructure seemed to reflect indifference to user experience. Leaving the Amsterdam airport, for instance, I expected there to be a big, obvious sign saying 'TRAINS TO CITY THIS WAY.' But the train signs were small and easy to miss, and more importantly, they named the final station the train was going to, which is meaningful to people who already know where they're going rather than newcomers.

Likewise, when I board the [3 train](https://en.wikipedia.org/wiki/3_(New_York_City_Subway_service)) to New Lots Avenue in New York, I _know_ that's going South and East to or through Brooklyn because I ride it a lot. But if you didn't, I think it would be very confusing. 

Some stations have maps, but _needing_ a guide is a kind of UX failure. Good user experience looks like a child picking up a video game controller for the first time and immediately figuring out how to play Bad UX looks like tourists' puzzling over a map in a loud, chaotic environment.

It's easy to criticize tech culture for its excesses and ideologies. But I think that our caring about our users' journeys so much that we formalized the practice into a career track is one thing we profoundly get right. So it's refreshing to hear that the practice informed LaGuardia's redesign.