---
title: It's weird that no one on "The Good Place" wants children
author: Seth Green
date: '2020-10-13'
slug: it-s-bizarre-that-no-one-on-the-good-place-has-or-wants-children
categories: []
tags: []
---

**(Spoilers for the whole show)**

because the show draws so obviously from conservative, christian beliefs about the purpose of life.

One of the people I watched _The Good Place_ with speculated that the show features zero children in the afterlife, where most of the action takes place, because no one wants to think about dead kids. I'm fine with that; it is, ultimately, a network sitcom, the kind of show you watch because it offers familiar faces^[The show winks at this expectation with [a fun scene of Ted Danson bartending](https://www.cinemablend.com/television/2454309/cheers-vet-ted-danson-was-uncomfortable-going-back-behind-the-bar-on-the-good-place). The people I watched it with were the right age to have watched _Cheers_'s original run, and that was a visual reference they appreciated. My relationship to _Cheers_ is more mediated: I think of The Ice King on _Adventure Time_ [singing the show's theme song](https://www.youtube.com/watch?v=6rdvgvvvVPk), trying to keep touch with reality as mania overcomes him. "Making your way in the world today," he sings, tremulously, nearly sobbing. Simon trusts TV, for it always gives, never asks too much, is never too tired to offer solace. "Television!" Homer says. ["Teacher, mother; secret lover."](https://www.youtube.com/watch?v=DumCuR4mdpQ) "The true American art form," opines [Kenneth Parcell](https://www.imdb.com/title/tt0920916/characters/nm1442113).]  and comfortable pleasures. For me, it evoked a time when pretty much everyone I knew watched the same shows, and whether they were 'good' or not was sort of besides the point, because they were something to talk about. (This was not the only nostalgia I indulged during the pandemic.)

But the series finale, where the characters each pursue their visions of the good life in the actual good place, is a lot weirder than it might seem at first. We watch Jason train to play the world's best game of [_Madden_](https://en.wikipedia.org/wiki/Madden_NFL), Tahani learn to [make chairs and burp the alphabet](https://www.reddit.com/r/TheGoodPlace/comments/exddu9/part_of_tahanis_list/), and Chidi and Eleanor have a lovely dinner with old friends (their ideal good life, it seems, is being childless, living in a city, well off, and in your 30s, forever). Each reconciles or reunites with their parents. 

But none of them has children; as far as the audience sees, none of them even contemplates it. Back here on Earth, lots of people who have kids, ahem, seem to find meaning in it:

> [My own informal research says that grandparent couples are happy couples](https://www.arnoldkling.com/blog/off-topic-marriage-and-grandchildren/). Some of that is selection bias–if you stuck it out as a couple long enough to have your grandchildren born, you are in good shape as a couple. But I think that some of it is that if you have children, then you want grandchildren, and when they arrive you feel real joy and satisfaction.

> [Here is the meaning of life:](https://en.wikipedia.org/wiki/Shadow_Puppets) ...to make babies with her, with him, or to find them some other way, but then to raise them up, and watch them do the same thing, generation after generation, so that when you die you know you are permanently a part of the great web of life. That you are not a loose thread, snipped off.

What these writers -- Arnold Kling and Orson Scott Card, respectively -- have in common is that their politics could be called conservative, and conservative ideas don't get a lot of explicit attention on scripted TV. But what's bizarre here is that _The Good Place_ is an _extremely_ conservative, religious show at its core. It's a story about a bunch of people who discover that there really is a judge, that there really is a heaven, and that the key to getting there is to live a good life as defined by a book of rules. Hell, the show even commits to the idea that the modern world is too complex to be unambiguously good in, thereby implicitly pining for, get this, _a pre-modern existence_. That's not even conservative, that's closer to reactionary.

Therein lies the deep weirdness at the heart of _The Good Place_. The words coming out of its characters' mouths, and the choices they pursue, are Very Right Now, very urban liberal, but its core conceit is that Christianity is 100% right about the big stuff (heaven, hell, creation, angels, demons, etc.). One way the show tries to thread this needle is by steering clear of any subject that brings this tension to the fore -- that is, anything implying that there's more to life than our own pleasure. All in all, it makes for a show that's a lot of fun to watch, but strange to think about once you've finished. 

5/5 stars, would recommend

