---
title: Having your social justice cake and eating well too
author: Seth Green
date: '2022-03-15'
slug: having-your-social-justice-cake-and-eating-well-too
categories: []
tags: []
---

A few years ago, a friend was doing a prestigious postdoc at a prominent law school. One time, a scholar who was in town for a seminar asked to be taken to a thousand-dollar-a-head restaurant,^[If you are a big-shot academic in one of the well off disciplines, the norm is that other schools will cover your flight, hotels, and meals if you come and give a lecture Typically, this involves one very nice dinner.] and it was my friend's responsibility to clear that with their department chair -- who promptly said, more or less, "no problem." So out they went, my friend, the visiting scholar, and a few others; and thus did the school spend something like 10% of a law student's yearly tuition on a single dinner. 

My friend's research has a clear pro-social, human-focused agenda, and they are a member of an intersectionally underrepresented group among law school faculty, so in two important respects, they and their career advance social justice. They are also, as a law school professor, earning something in the ballpark of what a first year associate at a big law firm would earn,^[Caveat that if they had gone biglaw right after law school, they would currently be many years into it, and undoubtedly would be outstanding in that field as well.] and, as the above story illustrates, the job comes with some perks that you might typically associate with people one or two levels [up the economic ladder](https://ofdollarsanddata.com/climbing-the-wealth-ladder/).

Is this not quite the feat? For reasons of taste and history, the job actively selects for a social justice research agenda, while simultaneously allowing you to sidestep the lifestyle trade-offs that we associate with social justice careers -- a [social worker's salary](https://www.salary.com/research/salary/benchmark/social-worker-msw-salary/new-orleans-la), a public defender's [overstuffed docket](https://thelensnola.org/2021/01/20/the-system-is-at-a-breaking-point-new-da-public-defenders-work-to-reduce-backlog-of-cases-at-criminal-district-court/),^[This is not to say that a given public defender is working harder, or doing more to advance justice, than my friend.] the [heartbreak and burnout](https://www.childwelfare.gov/topics/management/workforce/workforcewellbeing/burnout/) of working directly with at-risk youth. In other words, the job confers both the status benefits of a social justice career and the lifestyle benefits of [joining the PMC](https://www.thebellows.org/the-double-horseshoe-theory/).

A related phenomenon: a lot of LinkedIn posts tell what I think of as a ['Juicy'](https://en.wikipedia.org/wiki/Juicy_(The_Notorious_B.I.G._song)) narrative  -- "It was all a dream/I used to read Word Up! magazine," etc. Juicy posts start out with a story of hardship, like an impoverished childhood, and end with a clear-cut status success, like an acceptance into Harvard or a job at Meta. 

In a different era, we would have called these ['Horatio Alger' stories](https://en.wikipedia.org/wiki/Horatio_Alger). Their message is that because the authors started out with little, their successes can be attributed to talent and grit. Such stories also, I think, affirm that we live in a meritocracy where hard-working folks from under-represented groups can succeed, even if they faced discrimination and prejudice along the way, which damn the system as a whole. It's a fine balance to strike, but Juicy posts celebrate and affirm the American myth while simultaneously decrying systemic injustices.^['Juicy' the song also effectively strikes this balance. It's a little less plausible, to me, when Drake tries to ring the same bell in '[started from the bottom](https://en.wikipedia.org/wiki/Started_from_the_Bottom).']

If [yrstruly](https://infinitejest.wallacewiki.com/david-foster-wallace/index.php?title=M) announced such an accomplishment with the same fanfare, it would be, I think, pretty gauche. There is nothing even remotely social justice-y about my [climbing the greasy pole](https://www.theguardian.com/money/2001/apr/15/workandcareers.madeleinebunting3); in fact, because status is [fundamentally zero sum](http://daviddfriedman.blogspot.com/2006/10/economics-of-status.html), my doing so is (implicitly) denying opportunities to people with fewer privileges.

And thus are certain folks empowered to have their social justice cake and eat well too. Just being yourself suffices for advancing equity and representation, and whether it's ethical to [take a job at Meta in the first place](https://techpolicy.press/is-it-ethical-to-work-at-facebook/) is back of mind. 

I would not call this the main way in which the overarching system of our lives is reified, turning would-be firebrands into people whose crusades are more within the lines. But it is one way in which we swim with the currents. 
