---
title: '''Bad Hombres'' movies'
author: Seth Green
date: '2024-11-12'
categories:
  - movies
tags:
  - movies
slug: bad-hombres-movies
---

It's a conservative trope that Hollywood [hates](https://www.nationalreview.com/corner/west-hollywood-resolution-to-remove-trump-from-walk-of-fame/) [Trump](https://www.nationalreview.com/corner/steven-spielbergs-anti-trump-movie-post-meryl-streep-and-tom-hanks/), [Republicans](https://www.nationalreview.com/2018/03/oscars-liberal-bias-full-display-this-year/), and all they [hold dear](https://www.washingtontimes.com/news/2024/mar/9/hollywoods-radical-left-reality/). But we still get movies with fundamentally Trump-y themes animating them. Consider what we might call the '[bad hombres](https://www.pbs.org/newshour/politics/trumps-bad-hombres-draws-jeers-spanish-lessons)' genre:

-   [*Silent Night*](https://en.wikipedia.org/wiki/Silent_Night_(2023_film)#Critical_response), in which a (white) man seeks vengeance against (Latino) gangsters in southern California after they kill his son
-   [*Peppermint*](https://en.wikipedia.org/wiki/Peppermint_(2018_film)), which has the same plot except it stars Jennifer Garner
-   [Brawl in Cell Block 99](https://en.wikipedia.org/wiki/Brawl_in_Cell_Block_99), in which some bad, [multicultural](https://x.com/tszzl/status/1851054768728469508) gangsters try to ruin Vince Vaughn's life because he's prudent and ethically grounded (apparently its studio [has a populist bent](https://www.hollywoodreporter.com/movies/movie-news/how-cinestate-film-studio-is-turning-controversial-topics-revenue-1178338/))
-   ...probably others I haven't seen (ChatGPT suggests *The Marksman, Rambo: Last Blood*, and *Sicario).*

On the one hand, there's something unseemly about both sneering at these concerns and then seeking to profit from them. On the other, these stories were in our mythos when Trump descended the escalator.

(Personally I prefer movies like *The Forever Purge* and *The Hunt*, which approach the same material with a more sociological eye. The *Purge* movies in particular, I think, are likely to be remembered as more effectively zeitgeist-y than either the bad hombres movies or the _Civil War_.)
